const DATA_VERSION = '2026-09-12-v33';
const PRODUCTS = [
  {
    "model": "G13",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/G13.jpg",
    "bt": "BT 5.3",
    "power": "Charger 5V/2.4 A",
    "ports": "2x USB-A, TF Card Slot",
    "features": "Lossless Sound, Voice Assistant, Hands-free Call, TF Card Slot, U Disk Play, Dual USB",
    "signal": "10-15 m",
    "dim": "71 x 45 x 98.5 mm",
    "fm": "87.5-108.0 MHz",
    "selling": "🌈Bluetooth 5.3​ - 10m stable connection\n🔥 Dual USB ports​ - 5V/1A (music playback) + 5V/2.1A (fast charge)\n✅ Multi-playback​ - Supports TF card/USB/Bluetooth/FM",
    "desc": "Product Name: G13 Car FM Transmitter\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nTransmission Distance: 10-15m\nOutput ports: 2\nUSB-A1 output: 5V/1A(Supports u-disk media playback)\nUSB-A2 output: 5V/2.1A\nTF card Slot: 1\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters",
    "proto": "A2DP",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "G15",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/G15.jpg",
    "bt": "BT 5.3",
    "power": "Charger 5V/3.5 A",
    "ports": "2x USB-A, TF Card Slot",
    "features": "Lossless Sound, Voice Assistant, Hands-free Call, TF Card Slot, U Disk Play, Dual USB",
    "signal": "10-15 m",
    "dim": "71 x 45 x 98.5 mm",
    "fm": "87.5-108.0 MHz",
    "selling": "🌈 Bluetooth 5.3​ - 10m stable connection\n🔥 Dual USB ports​ - 5V/1A (music playback) + 5V/2.1A (fast charge)\n✅ Multi-playback​ - Supports TF card/USB/Bluetooth/FM",
    "desc": "Product Name: G15 Car FM Transmitter\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nTransmission Distance: 10-15m\nOutput ports: 2\nUSB-A1 output: 5V/1A(Supports u-disk media playback)\nUSB-A2 output: 5V/2.1A\nTF card Slot: 1\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters",
    "proto": "A2DP",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "G24",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/G24.jpg",
    "bt": "BT 5.3",
    "ports": "3x USB-A, 3.5mm AUX, TF Card Slot",
    "features": "Lossless Sound, QC3.0, Voice Assistant, Hands-free Call, TF Card Slot, U Disk Play",
    "signal": "10-15 m",
    "dim": "93.5 x 84 x 177 mm",
    "weight": "97.5 g",
    "fm": "87.5-108.0 MHz",
    "screen": "2.0 in",
    "selling": "🌈 2\" HD Color LCD​ - Vibrant display for easy control\n⚡ QC3.0 18W Fast Charge​ - Power devices at max speed\n🔋 3-Port Charging Hub​ - Charge 3 devices + play music simultaneously",
    "desc": "Product Name: G24 Car FM Transmitter with Colorful LCD Screen\nScreen:2.0 in HD color screen\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nTransmission Distance: 10-15m\nOutput ports: 3\nUSB-A1 output: 5V/1A(Supports u-disk media playback)\nUSB-A2 output: 5V/2.1A\nUSB-A3 output: QC3.0 18W\nTF card Slot: 1\n3.5mm Aux Output Port: 1\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters",
    "p_sample": "64.0",
    "p_500": "66.0",
    "p_2000": "65.0",
    "p_5000": "64.0",
    "acc": "User Manual, 3.5mm Audio Cable",
    "proto": "A2DP, QC3.0",
    "product_nw": "97.5 g",
    "box_gw": "200.0 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "G32",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/G32-Standard.jpg",
    "bt": "BT 5.4",
    "power": "Charger 5V/3.1 A",
    "features": "One Key Answer, Hands-free Call, TF Card Slot, U Disk Play, Universal for Cars",
    "dim": "70.5 x 46 x 98 mm",
    "proto": "A2DP",
    "p_sample": "23.0",
    "p_500": "22.0",
    "p_2000": "21.0",
    "p_5000": "20.0",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "G32-PD",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/G32-Standard.jpg",
    "bt": "BT 5.4",
    "power": "Charger 5V/3.1 A",
    "features": "Fast Charge, One Key Answer, Hands-free Call, TF Card Slot, U Disk Play, Universal for Cars",
    "dim": "70.5 x 46 x 98 mm",
    "proto": "A2DP",
    "p_sample": "23.0",
    "p_500": "22.0",
    "p_2000": "21.0",
    "p_5000": "20.0",
    "ports": "PD",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "G32-QC",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/G32-Standard.jpg",
    "bt": "BT 5.4",
    "power": "Charger 5V/3.1 A",
    "features": "QC3.0, One Key Answer, Hands-free Call, TF Card Slot, U Disk Play, Universal for Cars",
    "dim": "70.5 x 46 x 98 mm",
    "proto": "A2DP, QC3.0",
    "p_sample": "23.0",
    "p_500": "22.0",
    "p_2000": "21.0",
    "p_5000": "20.0",
    "ports": "QC3.0",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "G32-Uni",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/G32-Standard.jpg",
    "bt": "BT 5.3",
    "power": "Charger 5V/3.1 A",
    "features": "One Key Answer, Hands-free Call, TF Card Slot, U Disk Play, Universal for Cars",
    "dim": "70.5 x 46 x 98 mm",
    "proto": "A2DP",
    "p_sample": "23.0",
    "p_500": "22.0",
    "p_2000": "21.0",
    "p_5000": "20.0",
    "ports": "2x USB-A, TF Card Slot",
    "fm": "87.5-108.0 MHz",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "G45",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/G45-Standard.jpg",
    "bt": "BT 5.3",
    "power": "QC3.0 5V/1.0A",
    "ports": "3x USB-A, 3.5mm AUX, TF Card Slot",
    "features": "Lossless Sound, HD Sound, QC3.0, Voice Assistant, One Key Answer, Hands-free Call, TF Card Slot",
    "signal": "10-15 m",
    "dim": "105 x 57.5 x 136 mm",
    "weight": "94.8 g",
    "fm": "87.5-108.0 MHz",
    "color": "Black",
    "screen": "0.96 in",
    "selling": "🖥️0.96\" HD Color Screen​ - Compact yet crystal-clear display\n⚡️ QC3.0 18W Turbo Charge​ - Fastest in-car charging\n🔌️Triple-Port Power Hub​ - Charge 3 devices + music playback",
    "desc": "Product Name: G45 Car FM Transmitter with Colorful LCD Screen\nDisplay Screen:0.96 in HD color screen\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nTransmission Distance: 10-15m\nOutput ports: 3\nUSB-A1 output: 5V/1A(Supports u-disk media playback)\nUSB-A2 output: 5V/2.1A\nUSB-A3 output: QC3.0 18W\nTF card Slot: 1\n3.5mm Aux Output Port: 1\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters",
    "p_sample": "58.0",
    "p_500": "57.0",
    "p_2000": "56.0",
    "p_5000": "55.0",
    "acc": "User Manual, 3.5mm Audio Cable",
    "proto": "QC3.0",
    "product_nw": "94.8 g",
    "box_gw": "140.0 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "G45-C",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/G45-Standard.jpg",
    "bt": "BT 5.4",
    "power": "QC3.0 5V/1.0A",
    "ports": "3x USB-A, 3.5mm AUX, TF Card Slot",
    "features": "Lossless Sound, HD Sound, Voice Assistant, One Key Answer, Hands-free Call, TF Card Slot",
    "signal": "10-15 m",
    "dim": "105 x 57.5 x 136 mm",
    "weight": "94.8 g",
    "fm": "87.5-108.0 MHz",
    "color": "Black",
    "screen": "0.96 in",
    "selling": "🖥️0.96\" HD Color Screen​ - Compact yet crystal-clear display\n⚡️ QC3.0 18W Turbo Charge​ - Fastest in-car charging\n🔌️Triple-Port Power Hub​ - Charge 3 devices + music playback",
    "desc": "Product Name: G45 Car FM Transmitter with Colorful LCD Screen\nDisplay Screen:0.96 in HD color screen\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nTransmission Distance: 10-15m\nOutput ports: 3\nUSB-A1 output: 5V/1A(Supports u-disk media playback)\nUSB-A2 output: 5V/2.1A\nUSB-A3 output: QC3.0 18W\nTF card Slot: 1\n3.5mm Aux Output Port: 1\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters",
    "p_sample": "58.0",
    "p_500": "57.0",
    "p_2000": "56.0",
    "p_5000": "55.0",
    "acc": "User Manual, 3.5mm Audio Cable",
    "proto": "QC3.0",
    "product_nw": "94.8 g",
    "box_gw": "140.0 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "G47",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/G47-Standard.jpg",
    "bt": "BT 5.4",
    "ports": "Dual USB-A",
    "features": "Colorful Lights, 7 Color Modes, Lossless Sound, HD Mic, Fast Charge, TF Card Slot, U Disk Play, Power-off Memory",
    "dim": "70.5 x 46 x 98 mm",
    "color": "Black",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "p_sample": "22.0",
    "p_500": "21.0",
    "p_2000": "20.0",
    "p_5000": "19.0",
    "year": ""
  },
  {
    "model": "G47-Knob",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/G47-Standard.jpg",
    "bt": "BT 5.4",
    "ports": "Dual USB-A",
    "features": "Colorful Lights, 7 Color Modes, Lossless Sound, HD Mic, Fast Charge, U Disk Play, Power-off Memory",
    "dim": "70.5 x 46 x 98 mm",
    "color": "Black",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "p_sample": "22.0",
    "p_500": "21.0",
    "p_2000": "20.0",
    "p_5000": "19.0",
    "year": ""
  },
  {
    "model": "G47-Uni",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/G47-Standard.jpg",
    "bt": "BT 5.3",
    "ports": "2x USB-A, 1x USB-C, TF Card Slot",
    "features": "Colorful Lights, 7 Color Modes, Lossless Sound, HD Mic, Fast Charge, TF Card Slot, U Disk Play, Power-off Memory",
    "dim": "70.5 x 46 x 98 mm",
    "color": "Black",
    "fm": "87.5-108.0 MHz",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "p_sample": "22.0",
    "p_500": "21.0",
    "p_2000": "20.0",
    "p_5000": "19.0",
    "year": ""
  },
  {
    "model": "G52",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙耳机",
    "type_en": "Car MP3 Player",
    "image": "images/G52.jpg",
    "bt": "BT 5.3",
    "ports": "Type-C | QC3.0",
    "features": "Lossless Sound, QC3.0, Voltage Monitor, TF Card Slot, Private Answer, Universal for Cars",
    "signal": "10-15 m",
    "dim": "76 x 50 x 133 mm",
    "fm": "87.5-108.0 MHz",
    "color": "White",
    "selling": "🎧 Built-in Bluetooth Earphone​ - Private calls while driving (no extra headset needed)\n⚡ Fast Charging​ - QC3.0 18W (USB-A)\nBonus: Bluetooth 5.3 (10m) + FM playback",
    "desc": "Product Name: G52 Car FM Transmitter with Built-in Bluetooth earphone\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nTransmission Distance: 10-15m\nBuilt-in Bluetooth earphone: easy private calls while driving\nOutput ports: 2\nUSB-A output: QC3.0 18W\nUSB-C output: 5V/3.0A\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters",
    "proto": "QC3.0",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "G57",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙耳机",
    "type_en": "Car MP3 Player",
    "image": "images/G57.jpg",
    "bt": "BT 5.3",
    "ports": "Type-C | QC3.0",
    "features": "Lossless Sound, QC3.0, Hands-free Call, Private Answer, Universal for Cars",
    "signal": "10-15 m",
    "dim": "74 x 50 x 111 mm",
    "fm": "87.5-108.0 MHz",
    "color": "White",
    "selling": "🎧 Built-in Bluetooth Earphone​ - Private calls while driving (no extra headset needed)\n⚡ Fast Charging​ - QC3.0 18W (USB-A)\nBonus: Bluetooth 5.3 (10m) + FM playback",
    "desc": "Product Name: G57 Car FM Transmitter with Built-in Bluetooth earphone\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nTransmission Distance: 10-15m\nBuilt-in Bluetooth earphone: easy private calls while driving\nOutput ports: 2\nUSB-A output: QC3.0 18W\nUSB-C output: 5V/3.0A\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters",
    "proto": "QC3.0",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "G61",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/G61.jpg",
    "bt": "BT 5.3",
    "ports": "TF Card Slot",
    "features": "Colorful Lights, 7 Color Modes, Lossless Sound, HD Mic, Fast Charge, QC3.0, TF Card Slot",
    "signal": "10-15 m",
    "dim": "67 x 47 x 104 mm",
    "weight": "30.0 g",
    "fm": "87.5-108.0 MHz",
    "color": "Black",
    "selling": "⚡️ QC3.0 18W Turbo Charge​ - Fastest in-car charging\n💡 Smart Ambient Lighting\n📊 Shows FM + Battery Voltage simultaneously\nBonus: Bluetooth 5.3 (10m) + TF/USB/FM playback",
    "desc": "Product Name: G61 Car FM Transmitter\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nLED Display: FM/Car battery Voltage display\nTransmission Distance: 10-15m\nOutput ports: 2\nUSB-A output: QC3.0 18W\nUSB-C output: 5V/3.0A\nTF card Slot: 1\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters\nOthers Features: Built-in ambient lighting",
    "p_sample": "33.0",
    "p_500": "32.0",
    "p_2000": "31.0",
    "p_5000": "30.0",
    "acc": "User Manual",
    "proto": "QC3.0",
    "product_nw": "30.0 g",
    "box_gw": "54.2 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "G67",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/G67.jpg",
    "bt": "BT 5.3",
    "ports": "2x USB-A, 1x USB-C, TF Card Slot",
    "features": "Colorful Lights, 7 Color Modes, Lossless Sound, HD Mic, Fast Charge, Voice Navigation, TF Card Slot, U Disk Play, Stereo, Universal for Cars, Power-off Memory, FM Transmit",
    "signal": "10-15 m",
    "dim": "70.5 x 46 x 98 mm",
    "weight": "32.0 g",
    "fm": "87.5-108.0 MHz",
    "color": "Black",
    "selling": "⚡ Fast Charging​ - PD20W (USB-C) + QC3.0 18W (USB-A)\n💡 Smart Ambient Lighting\n📊 Shows FM + Battery Voltage simultaneously\nBonus: Bluetooth 5.3 (10m) + TF/USB/FM playback",
    "desc": "Product Name: G67-A1C Car FM Transmitter\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nLED Display: FM/Car battery Voltage display\nTransmission Distance: 10-15m\nOutput ports: 3\nUSB-A1 output: 5V/1A(Supports u-disk media playback)\nUSB-A2 output: 5V/3A, 9V/2A, 12V/1.5A (QC3.0 18W)\nUSB-C1 output: PD 20W\nTF card Slot: 1\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters\nOthers Features: Built-in ambient lighting",
    "acc": "User Manual",
    "product_nw": "32.0 g",
    "box_gw": "55.0 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "p_sample": "21.0",
    "p_500": "20.0",
    "p_2000": "19.0",
    "p_5000": "18.0",
    "year": ""
  },
  {
    "model": "G68",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/G68.jpg",
    "bt": "BT 5.3",
    "ports": "2x USB-A, 1x USB-C, TF Card Slot",
    "features": "Colorful Lights, Heavy Bass, Lossless Sound, HD Mic, Fast Charge, TF Card Slot, Universal for Cars, Spaceship Design",
    "signal": "10-15 m",
    "dim": "78 x 59 x 115 mm",
    "weight": "40.2 g",
    "fm": "87.5-108.0 MHz",
    "input_v": "12V/24V DC",
    "color": "Black",
    "selling": "💡 Smart Ambient Lighting\n📊 Shows FM + Battery Voltage simultaneously\nBonus: Bluetooth 5.3 (10m) + TF/USB/FM playback",
    "desc": "Product Name: G68 Car FM Transmitter\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nLED Display: FM/Car battery Voltage display\nTransmission Distance: 10-15m\nOutput ports: 3\nUSB-A1 output: 5V/1A(Supports u-disk media playback)\nUSB-A2 output: 5V/3.0A\nUSB-C1 output: 5V/3.0A\nTF card Slot: 1\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters\nOthers Features: Built-in ambient lighting",
    "p_sample": "22.0",
    "p_500": "21.0",
    "p_2000": "20.0",
    "p_5000": "19.0",
    "acc": "User Manual",
    "product_nw": "40.2 g",
    "box_gw": "72.0 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GC01",
    "category": "Car Charger",
    "type_cn": "一分三车充",
    "type_en": "Smart USB Car Charger",
    "image": "images/GC01.jpg",
    "power": "Total 120W",
    "ports": "3x USB-A, 2x USB-C",
    "features": "LED Display, Independent Switch, Stereo, Universal for Cars",
    "dim": "74 x 122 x 38mm",
    "weight": "193.0 g",
    "cable": "1.0m",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "color": "Black",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "🔌 3-in-1 Power Hub:​ Combines 3 cigarette lighter sockets and 5 USB ports (3A+2C) in one device\n⚡ 120W Max Power & 36W PD:​ Supports high-power car appliances and fast charges devices via PD (5V/3A, 9V/3A, 12V/3A)\n🛡 Safe & Smart Design:​ Built with fireproof PC+ABS, multi-protection, and a car battery voltage LED display",
    "desc": "1-to-3 Car Charger\nVoltage Range: 6-30V\nInput Voltage: 12V-24V\nTotal Output Power: 120W\nOutput Ports: 5\nUSB 1 Output: 5V/2.1A\nUSB 2 Output: 5V/2.1A\nUSB 3 Output: 5V/2.1A\nType-C 1 Output: 5V/2.1A\nType-C 2 Output: 5V/3.1A\nProduct Material: Plastic\nIndependent Switch Control\nPower Cable Length: 100cm\n3Cigarette Lighter Illumination Sockets\nCertification: CE FCC RoHS Design Patent",
    "p_sample": "36.0",
    "p_500": "35.0",
    "p_2000": "34.0",
    "p_5000": "33.0",
    "acc": "User Manual x1",
    "product_dim": "74 x 122 x 38mm",
    "box_dim": "135 x 125 x 45mm",
    "carton_dim": "34 x 29.3 x 49.5cm",
    "qty_carton": "50pcs/carton",
    "product_nw": "193.0 g",
    "box_gw": "250.0 g",
    "carton_gw": "",
    "year": ""
  },
  {
    "model": "GC01-A1C",
    "category": "Car Charger",
    "type_cn": "一分三车充",
    "type_en": "Smart USB Car Charger",
    "image": "images/GC01.jpg",
    "power": "Total 120W",
    "ports": "3x USB-A, 2x USB-C",
    "features": "LED Display, QC3.0, Independent Switch, Stereo, Universal for Cars",
    "dim": "74 x 122 x 38mm",
    "weight": "193.0 g",
    "cable": "1.0m",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "color": "Black",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "🔌 3-in-1 Power Hub:​ Combines 3 cigarette lighter sockets and 5 USB ports (3A+2C) in one device\n⚡ 120W Max Power & 36W PD:​ Supports high-power car appliances and fast charges devices via PD (5V/3A, 9V/3A, 12V/3A)\n🛡 Safe & Smart Design:​ Built with fireproof PC+ABS, multi-protection, and a car battery voltage LED display",
    "desc": "Product Name: GC01 3-Socket Cigarette Lighter Splitter with 5-Port USB Car Charger (3A2C) \nPower Input Voltage: DC 12V-24V\nTotal Output Power: Max 120W\nOutput Port(s): 2 USB-C + 3 USB-A + 3 Cigarette Sockets\nUSB-A1 Output: 5V/2.4A\nUSB-A2 Output: 5V/2.4A\nUSB-A3 Output: 5V/2.4A\nUSB-C1 Output: 5V/2.4A\nUSB-C2 Output: 5V/3A, 9V/3A, 12V/3A (36W Max)\nSocket Extension Output: 120W Max\nFast Charge Protocols: PD 3.0, PPS, AFC, FCP, SCP\nDesign Material: Fireproof PC + ABS\nCable Length: 1.0m \nSafety Protections: OCP, OVP, OTP, Short Circuit Protection\nCertifications: CE, FCC, RoHS\nOthers Features: Car Battery Voltage LED Display",
    "p_sample": "36.0",
    "p_500": "35.0",
    "p_2000": "34.0",
    "p_5000": "33.0",
    "acc": "User Manual x1",
    "proto": "QC3.0",
    "product_dim": "74 x 122 x 38mm",
    "box_dim": "135 x 125 x 45mm",
    "carton_dim": "34 x 29.3 x 49.5cm",
    "qty_carton": "50pcs/carton",
    "product_nw": "193.0 g",
    "box_gw": "250.0 g",
    "carton_gw": "",
    "year": ""
  },
  {
    "model": "GC03",
    "category": "Car Charger",
    "type_cn": "车载充电器",
    "type_en": "Car Charger",
    "image": "images/GC03-Standard.jpg",
    "power": "PD 30W | Total 30W",
    "ports": "1x USB-A, 2x USB-C",
    "features": "Colorful Lights, Smart Protection, Universal for Cars",
    "dim": "35 x 40 x 71.5 mm",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "⚡ PD 36W USB-C Port​ - Fast charge compatible devices\n🔌1A2C Multi-Output​ - Charge three devices at once\n🛡Safe & Stylish​ - Fireproof build with ambient lighting",
    "desc": "Product Name: GC03 Car Charger PD36W(1A2C) \nPower Input Voltage: DC 12V-24V\nTotal Output Power: Max 51.5W\nOutput Port(s): 1 USB-A + 2 USB-C\nUSB-A1 Output: 5V/3.1A\nUSB-C1 Output: 5V/3.1A\nUSB-C2 Output: 5V/3A, 9V/3A, 12V/3A (36W Max)\nSocket Extension: 51.5W Max\nFast Charge Protocols: PD 3.0, PPS, AFC, FCP, SCP\nDesign Material: Fireproof PC + ABS\nSafety Protections: OCP, OVP, OTP, Short Circuit Protection\nCertifications: CE, FCC, RoHS\nOthers Features: Built-in ambient lighting",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GC03C",
    "category": "Car Charger",
    "type_cn": "车载充电器",
    "type_en": "Car Charger",
    "image": "images/GC03-Standard.jpg",
    "power": "Total 54W",
    "ports": "3x USB-C",
    "features": "Colorful Lights, Smart Protection, Universal for Cars",
    "dim": "35 x 40 x 71.5 mm",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "⚡ PD 36W USB-C Port​ - Fast charge compatible devices\n🔌1A2C Multi-Output​ - Charge three devices at once\n🛡Safe & Stylish​ - Fireproof build with ambient lighting",
    "desc": "Product Name: GC03 Car Charger PD36W(1A2C) \nPower Input Voltage: DC 12V-24V\nTotal Output Power: Max 51.5W\nOutput Port(s): 1 USB-A + 2 USB-C\nUSB-A1 Output: 5V/3.1A\nUSB-C1 Output: 5V/3.1A\nUSB-C2 Output: 5V/3A, 9V/3A, 12V/3A (36W Max)\nSocket Extension: 51.5W Max\nFast Charge Protocols: PD 3.0, PPS, AFC, FCP, SCP\nDesign Material: Fireproof PC + ABS\nSafety Protections: OCP, OVP, OTP, Short Circuit Protection\nCertifications: CE, FCC, RoHS\nOthers Features: Built-in ambient lighting",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GC03S",
    "category": "Car Charger",
    "type_cn": "车载充电器",
    "type_en": "Car Charger",
    "image": "images/GC03-Standard.jpg",
    "power": "PD 65W | Total 65W+18W",
    "ports": "1x USB-A, 2x USB-C",
    "features": "Colorful Lights, Voltage Monitor, Universal for Cars",
    "dim": "35 x 40 x 71.5 mm",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "⚡ PD 36W USB-C Port​ - Fast charge compatible devices\n🔌1A2C Multi-Output​ - Charge three devices at once\n🛡Safe & Stylish​ - Fireproof build with ambient lighting",
    "desc": "Product Name: GC03 Car Charger PD36W(1A2C) \nPower Input Voltage: DC 12V-24V\nTotal Output Power: Max 51.5W\nOutput Port(s): 1 USB-A + 2 USB-C\nUSB-A1 Output: 5V/3.1A\nUSB-C1 Output: 5V/3.1A\nUSB-C2 Output: 5V/3A, 9V/3A, 12V/3A (36W Max)\nSocket Extension: 51.5W Max\nFast Charge Protocols: PD 3.0, PPS, AFC, FCP, SCP\nDesign Material: Fireproof PC + ABS\nSafety Protections: OCP, OVP, OTP, Short Circuit Protection\nCertifications: CE, FCC, RoHS\nOthers Features: Built-in ambient lighting",
    "cable": "1.3 m",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GC03S-BlueLED",
    "category": "Car Charger",
    "type_cn": "车载充电器",
    "type_en": "Car Charger",
    "image": "images/GC03-Standard.jpg",
    "power": "PD 65W | Total 65W+18W",
    "ports": "USB-A + USB-C | PD | Retractable Cable",
    "features": "Colorful Lights, Voltage Monitor, Universal for Cars",
    "dim": "35 x 40 x 71.5 mm",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "⚡ PD 36W USB-C Port​ - Fast charge compatible devices\n🔌1A2C Multi-Output​ - Charge three devices at once\n🛡Safe & Stylish​ - Fireproof build with ambient lighting",
    "desc": "Product Name: GC03 Car Charger PD36W(1A2C) \nPower Input Voltage: DC 12V-24V\nTotal Output Power: Max 51.5W\nOutput Port(s): 1 USB-A + 2 USB-C\nUSB-A1 Output: 5V/3.1A\nUSB-C1 Output: 5V/3.1A\nUSB-C2 Output: 5V/3A, 9V/3A, 12V/3A (36W Max)\nSocket Extension: 51.5W Max\nFast Charge Protocols: PD 3.0, PPS, AFC, FCP, SCP\nDesign Material: Fireproof PC + ABS\nSafety Protections: OCP, OVP, OTP, Short Circuit Protection\nCertifications: CE, FCC, RoHS\nOthers Features: Built-in ambient lighting",
    "cable": "1.3 m",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GC05",
    "category": "Car Charger",
    "type_cn": "车载充电器",
    "type_en": "Car Charger",
    "image": "images/GC05.jpg",
    "power": "Total 120W",
    "ports": "3x USB-A, 3x USB-C",
    "features": "Colorful Lights, Fast Charge, QC3.0, Universal for Cars",
    "dim": "41 x 41 x 71mm\n46 x 20 x 65mm",
    "weight": "81.4 g",
    "cable": "1.5m",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "💡 1.5m cable extends 1A2C Plug to 2A1C splitter​ - Enabling Front and Rear Passengers to enjoy fast charging.\n🔌 3A3C 6-Port Design​ - Charge multiple devices simultaneously\n⚡  120W Max Power & PD 36W​ - High-power output with fast charging\n🛡️Safe & Smart​ - Fireproof build with ambient lighting & voltage display",
    "desc": "Voltage Range: 6-30V\nInput Voltage: 12V-24V\nOutput Ports: 6\nUSB Output: QC3.0 Fast Charging\nType-C 1 Output: PD 36W\nType-C 2 Output: PD 25W\nExpansion Type-C Output: PD 36W\nExpansion USB 1 Output: QC3.0 Fast Charging\nExpansion USB 2 Output: QC3.0 Fast Charging\nTotal Output Power: 115W\nLED Ambient Light: 7 Colors\nPower Cable Length: 150cm\nCertification: CE FCC RoHS Design Patent",
    "p_sample": "39.0",
    "p_500": "38.0",
    "p_2000": "36.0",
    "p_5000": "35.0",
    "acc": "User Manual x1",
    "proto": "SCP/FCP/AFC, QC2.0, QC3.0, PD3.0",
    "product_dim": "41 x 41 x 71mm\n46 x 20 x 65mm",
    "box_dim": "100 x 37 x 126mm",
    "carton_dim": "41.5 x 38.5 x 40cm",
    "qty_carton": "120pcs/carton",
    "product_nw": "81.4 g",
    "box_gw": "113.2 g",
    "carton_gw": "",
    "year": ""
  },
  {
    "model": "GC05-C",
    "category": "Car Charger",
    "type_cn": "车载充电器",
    "type_en": "Car Charger",
    "image": "images/GC05-C.jpg",
    "power": "Total 61W",
    "ports": "1x USB-A, 2x USB-C",
    "features": "Colorful Lights, Fast Charge, QC3.0, Voltage Monitor, Universal for Cars",
    "dim": "",
    "weight": "81.4 g",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "⚡  61W Total Power & PD 36W​ - High-power output with fast charging\n🔌 1A2C Multi-Output​ - Charge three devices at once\n🛡 Safe & Smart​ - Fireproof build with ambient lighting & voltage display",
    "desc": "Material: ABS+PC\nInput: 12V-24V\nCar Charger Output Ports:\nUSB: 5V/3A,9V/2A,12V/1.5A (QC3.0)\nUSB-C1: 5V/3.0A,9V/2.77A,12V/2.08A (PD 25W Max)\nUSB-C2: 5V/3A,9V/3A,12V/3A (PD 36W Max)\nUSB Port and USB-C2 Port Simultaneous Use, Output, shared 5V/3A\n6. Overall Max Output: 25W+36W",
    "p_sample": "24.0",
    "p_500": "23.0",
    "p_2000": "21.0",
    "p_5000": "20.0",
    "acc": "User Manual x1",
    "proto": "SCP/FCP/AFC, QC2.0, QC3.0, PD3.0",
    "box_dim": "70.5 x 46 x 98mm",
    "carton_dim": "50 x 21.5 x 38cm",
    "qty_carton": "100pcs/carton",
    "product_nw": "",
    "box_gw": "",
    "carton_gw": "",
    "product_dim": "",
    "year": ""
  },
  {
    "model": "GC13-45W",
    "category": "Car Charger",
    "type_cn": "多设备扩展车充",
    "image": "images/GC13-45W.jpg",
    "power": "PD 45W | Total 45W+18W+18W",
    "ports": "Dual USB-A | USB-A + USB-C | 2x USB-A | 2x USB-C | PD | Retractable Cable",
    "features": "Voltage Monitor, Smart Protection, Universal for Cars",
    "dim": "108 x 37 x 139 mm",
    "cable": "78CM",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GC15",
    "category": "Car Charger",
    "type_cn": "伸缩线车充",
    "type_en": "Car Charger",
    "image": "images/GC15.jpg",
    "power": "Total 65W",
    "ports": "1x USB-A, 3x USB-C, Retractable Cable",
    "features": "Colorful Lights, Smart Protection, 360° Rotation, Universal for Cars",
    "dim": "41.3 x 53 x 156.4mm",
    "weight": "114 g",
    "cable": "78cm",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "🔌 Dual 65W PD Retractable Cables​ - Features two built-in 78cm USB-C cables, with one supporting up to 65W PD fast charging.\n⚡ 83W High-Power Output​ - Delivers a combined 65W + 18W output for charging laptops, tablets, and phones simultaneously.\n🛡 Safe & Smart Design​ - Combines fireproof PC+ABS, comprehensive safety protections, ambient lighting, and a car battery voltage display.",
    "desc": "Total Output: Max 83W\nOutput Ports: 4\nPD Retractable Cable Output: 5V/3.0A,9V/3.0A,12V/3.0A,15V/3.0A,20V/3.25A(Max Power 65W),\nof which 15Vand 20VOutput only for 24Vvehicles\nUSB-C/iOS Retractable Cable + USB-C2 + USB-A Output: 5V/3.6A(Max Power 18W)\nTotal Output Power: Max 65W+18W\nRetractable Cable Length: Total Length 80cm\n(Effective Length 78cm ± 1cm)\nCar Charger Material: PC+ABS\n7-Color LED Light: One-Touch Switch",
    "p_sample": "50.0",
    "p_500": "39.0",
    "p_2000": "36.0",
    "p_5000": "35.0",
    "acc": "User Manual x1",
    "product_dim": "41.3 x 53 x 156.4mm",
    "box_dim": "73 x 45 x 182mm",
    "carton_dim": "47.5 x 38.2 x 31.5cm",
    "qty_carton": "80pcs/carton",
    "product_nw": "114 g",
    "box_gw": "152 g",
    "carton_gw": "",
    "year": ""
  },
  {
    "model": "GC16",
    "category": "Car Charger",
    "type_cn": "三核智能车充",
    "type_en": "Car Charger",
    "image": "images/GC16.jpg",
    "power": "Total 120W",
    "ports": "1x USB-A, 2x USB-C",
    "features": "Voltage Monitor, Smart Protection, Universal for Cars, Spring Wire",
    "dim": "97.5 x 59 x 36mm",
    "cable": "1.5 m",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "🔌 1-to-1 Cigarette Lighter Adapter with PD Spring Cable​ - Integrates a plug-in cigarette lighter socket and a retractable PD cable​ in a single, space-saving unit.\n⚡ 120W High Power & 65W PD​ - Delivers up to 120W​ through the socket and 65W​ via the retractable USB-C PD port for fast charging laptops and other high-power devices.\n🛡 Safe & Smart​ - Built-in car battery voltage display and comprehensive safety protections ensure reliable, worry-free use.",
    "desc": "Spring Cable USB-C Output: 5V 3.0A,9V 3.0A,12V 3.0A,15V 3.0A,20V 3.25A\n(24V vehicles support 15V/20V 65W Max, e.g. trucks, buses)\nUSB-C Output: 5V 3.0A, 9V 3.0A, 12V 3.0A ,15V 3.0A,20V 3.25A\n(24V vehicles support 15V/20V 65W Max, e.g. trucks, buses)\nUSB-A Output: 5V 3.0A, 9V 2.0A, 12V 1.5A QC18W\nTotal Output: Max PD 65W+Max PD 65W+QC18W\nWorking Temperature: -40℃~85℃\nFast Charging Protocol: AFC PPS PD3.0 QC2.0 SCP QC4.0 QC3.0",
    "p_sample": "29.0",
    "p_500": "28.0",
    "p_2000": "27.0",
    "p_5000": "26.0",
    "acc": "User Manual x1",
    "product_dim": "97.5 x 59 x 36mm",
    "box_dim": "85 x 40 x 116.5mm",
    "product_nw": "84g",
    "box_gw": "105.8g",
    "carton_gw": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GC18",
    "category": "Car Charger",
    "type_cn": "伸缩线车充",
    "type_en": "Car Charger",
    "image": "images/GC18.png",
    "power": "Total 120W",
    "ports": "1x USB-A, 2x USB-C, Retractable Cable",
    "features": "Colorful Lights, Smart Protection, 360° Rotation, Universal for Cars",
    "dim": "67 x 48 x 159mm",
    "cable": "80CM",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "🦉 Owl-Shaped Design​ - Unique car accessory with an integrated PD retractable cable.\n⚡ 120W Power & 65W PD​ - Features a 120W socket extension and a 65W USB-C PD port for fast charging laptops and multiple devices.\n🛡Safe & Smart​ - Built-in car battery voltage display and comprehensive safety protections.",
    "desc": "Working Voltage: 12V-24V\nVoltage Limit Range: 9-26V\nOutput Ports: 5\nUSB-A1 Port Output: 5V/3.6A\nUSB-C Port Output: 5V/3.6A(with A1, shared 18W)\nUSB-C1 Retractable Cable Output: PD Fast Charging 65W(Max 65W 15V/20V limited to 24V vehicles, e.g. trucks, buses)\n2 Extra Cigarette Lighter Socket Output: Shared Max120W,with 2Independent Switch\nRetractable Cable Length: 0.78m\nReal-Time Car Battery Voltage Display\nMaterial: Aluminum Alloy & ABS\nCertification: CE FCC RoHS Design Patent",
    "p_sample": "41.0",
    "p_500": "40.0",
    "p_2000": "39.0",
    "p_5000": "38.0",
    "acc": "User Manual x1",
    "product_dim": "67 x 48 x 159mm",
    "box_dim": "90 x 59 x 185mm",
    "carton_dim": "41.5 x 36.4 x 44.0cm",
    "qty_carton": "80pcs/carton",
    "product_nw": "130.2g",
    "box_gw": "251.8g",
    "carton_gw": "",
    "year": ""
  },
  {
    "model": "GC21",
    "category": "Car Charger",
    "type_cn": "车充表情款",
    "type_en": "Car Charger",
    "image": "images/GC21.jpg",
    "power": "Total 83W",
    "ports": "Retractable Cable",
    "features": "Voltage Monitor, Smart Protection, Universal for Cars, Emoji Display",
    "dim": "85 x 44 x 183 mm",
    "cable": "78CM",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "🦉 Cute Emoji Faces & Real-Time Voltage Display​ - Exclusive Cute Emojis, Switch Anytime You Like.\n⚡  Power 83W​ - a PD 65W Retractable Cable + 1A1C 18W for fast charging laptops and multiple devices.\n🛡Safe & Smart​ - Built-in car battery voltage display and comprehensive safety protections.",
    "desc": "Product Name: GC21 Emoji Car Charger with a PD65W Retractable Cable\nPower Input Voltage: DC 12V-24V\nTotal Output Power: Max 83W\nOutput Port(s): 1 USB-A + 1 USB-C + 1 PD65W Retractable Cable\nUSB-A Output: 5V/3.6A\nUSB-C Output: 5V/3.6A\nPD65W Retractable Cable Output: 5V/3A, 9V/3A, 12V/3A, 15V/3A, 20V/3.25A (Max 65W)\n\nA + C Total Output: 5V/3.6A 18W Shared\n\nSocket Extension Output: 83W Max\nFast Charge Protocols: PD 3.0, PPS, AFC, FCP, SCP\nDesign Material: Fireproof PC + ABS\nSafety Protections: OCP, OVP, OTP, Short Circuit Protection\nCertifications: CE, FCC, RoHS\nOthers Features: Cute Emoji faces & Car Battery Voltage LED Display",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "p_sample": "50.0",
    "p_500": "45.0",
    "p_2000": "42.0",
    "p_5000": "41.0",
    "year": ""
  },
  {
    "model": "GC21-Z",
    "category": "Car Charger",
    "type_cn": "车充表情款",
    "type_en": "Car Charger",
    "image": "images/GC21-Z.png",
    "power": "Total 83W",
    "ports": "Retractable Cable",
    "features": "Hands-free Call, Universal for Cars, FM Transmit",
    "dim": "85 x 44 x 183 mm",
    "cable": "78CM",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "🦉 Cute Emoji Faces & Real-Time Voltage Display​ - Exclusive Cute Emojis, Switch Anytime You Like.\n⚡  Power 83W​ - a PD 65W Retractable Cable + 1A1C 18W for fast charging laptops and multiple devices.\n🛡Safe & Smart​ - Built-in car battery voltage display and comprehensive safety protections.",
    "desc": "Product Name: GC21 Emoji Car Charger with a PD65W Retractable Cable\nPower Input Voltage: DC 12V-24V\nTotal Output Power: Max 83W\nOutput Port(s): 1 USB-A + 1 USB-C + 1 PD65W Retractable Cable\nUSB-A Output: 5V/3.6A\nUSB-C Output: 5V/3.6A\nPD65W Retractable Cable Output: 5V/3A, 9V/3A, 12V/3A, 15V/3A, 20V/3.25A (Max 65W)\n\nA + C Total Output: 5V/3.6A 18W Shared\n\nSocket Extension Output: 83W Max\nFast Charge Protocols: PD 3.0, PPS, AFC, FCP, SCP\nDesign Material: Fireproof PC + ABS\nSafety Protections: OCP, OVP, OTP, Short Circuit Protection\nCertifications: CE, FCC, RoHS\nOthers Features: Cute Emoji faces & Car Battery Voltage LED Display",
    "bt": "BT 5.4",
    "fm": "87.5 - 108.0 MHz",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "p_sample": "60.0",
    "p_500": "53.0",
    "p_2000": "52.0",
    "p_5000": "52.0",
    "year": ""
  },
  {
    "model": "GC24",
    "category": "Car Charger",
    "type_cn": "伸缩线车充",
    "type_en": "Car Charger",
    "image": "images/GC24.jpg",
    "power": "Total 65W",
    "ports": "1x USB-A, 2x USB-C, Retractable Cable",
    "features": "Voltage Monitor, Smart Protection, Universal for Cars",
    "dim": "52 x 34 x 128.8mm",
    "cable": "78cm",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "🔌 Built-in 65W PD retractable cable\n⚡   83W total output (65W+18W)\n🛡 Safe with fireproof PC+ABS and voltage display",
    "desc": "Input Voltage: DC 12V-24V\nTotal Output Power: Max 83W\nRetractable Cable Length: 78cm±1cm\nPD Retractable Cable Output: 5V/3.0A,9V=3.0A,\n12V/3.0A,15V/3.0A,\n20V/3.25A (24V vehicles support 15V/20V65W Max,e.g. trucks, buses)\nUSB-A+USB-C Output: 5V/3.6A(Shared 18W)\nVoltage Display Range: 11V-15V\nWorking Temperature: -20°C~60°C\nStorage Temperature: -30°C~85°C\n\nMaterial: ABS+PC Fireproof Material",
    "p_sample": "39.0",
    "p_500": "37.0",
    "p_2000": "36.0",
    "p_5000": "35.0",
    "acc": "User Manual x1",
    "product_dim": "52 x 34 x 128.8mm",
    "box_dim": "71 x 151 x 38mm",
    "product_nw": "75.6g",
    "box_gw": "109.6g",
    "carton_gw": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GC24-Boost",
    "category": "Car Charger",
    "type_cn": "伸缩线车充",
    "type_en": "Car Charger",
    "image": "images/GC24.jpg",
    "power": "PD 65W | Total 65W+18W",
    "ports": "USB-A + USB-C | PD | Retractable Cable",
    "features": "Voltage Monitor, Smart Protection, Universal for Cars",
    "dim": "71 x 151 x 38 mm",
    "cable": "78CM",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "🔌 Built-in 65W PD retractable cable\n⚡   83W total output (65W+18W)\n🛡 Safe with fireproof PC+ABS and voltage display",
    "desc": "Input Voltage: DC 12V-24V\nTotal Output Power: Max 83W\nRetractable Cable Length: 78cm±1cm\nPD Retractable Cable Output: 5V/3.0A,9V=3.0A,\n12V/3.0A,15V/3.0A,\n20V/3.25A (24V vehicles support 15V/20V65W Max,e.g. trucks, buses)\nUSB-A+USB-C Output: 5V/3.6A(Shared 18W)\nVoltage Display Range: 11V-15V\nWorking Temperature: -20°C~60°C\nStorage Temperature: -30°C~85°C\n\nMaterial: ABS+PC Fireproof Material",
    "p_sample": "39.0",
    "p_500": "37.0",
    "p_2000": "36.0",
    "p_5000": "35.0",
    "acc": "User Manual x1",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GC25",
    "category": "Car Charger",
    "type_cn": "伸缩线车充",
    "image": "images/GC25.jpg",
    "power": "PD 65W | Total 65W+18W",
    "ports": "USB-A + USB-C | PD | Retractable Cable",
    "features": "Colorful Lights, Smart Protection, Universal for Cars",
    "cable": "78CM",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "ZNB02",
    "category": "Car Charger",
    "type_cn": "一拖二车充",
    "type_en": "Smart USB Car Charger",
    "image": "images/ZNB02-C.jpg",
    "power": "Total 120W",
    "ports": "2x USB-A",
    "features": "Voltage Monitor, Independent Switch, Universal for Cars, Dual USB",
    "dim": "40 x 50 x 120mm",
    "weight": "125.0 g",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "🔌 2-in-1 Power Hub:​ Combines 2 cigarette lighter sockets and 2 USB-A ports, expanding your car’s power supply.\n⚡ 120W High Power:​ Delivers up to 120W total output, with 80W dedicated to the sockets for high-power car accessories.\n🛡️ Safe & Smart:​ Built with fireproof PC+ABS, comprehensive safety protections, and a car battery voltage LED display.",
    "desc": "1-to-2 Car Charger\nVoltage Display Range: 6-30V\nInput Voltage: 12V-24V\nTotal Output Power: 80W\nOutput Ports: 2\nUSB 1 Output: 5V 3.1A\nUSB 2 Output: QC3.0 Fast Charging\nDisplay: Digital\nPower Cable Length: 100cm\n2Cigarette LighterInterface\nIndependent Switch Control\nCertification: CE FCC RoHS Design Patent",
    "p_sample": "39.0",
    "p_500": "38.0",
    "p_2000": "36.0",
    "p_5000": "35.0",
    "acc": "User Manual x1",
    "product_dim": "40 x 50 x 120mm",
    "box_dim": "48 x 86 x 130mm",
    "carton_dim": "47 x 35 x 38cm",
    "qty_carton": "100pcs/carton",
    "product_nw": "125.0 g",
    "box_gw": "165.0 g",
    "carton_gw": "",
    "year": ""
  },
  {
    "model": "ZNB02-LED",
    "category": "Car Charger",
    "type_cn": "一拖二车充",
    "type_en": "Smart USB Car Charger",
    "image": "images/ZNB02-C.jpg",
    "power": "Total 120W",
    "ports": "2x USB-A",
    "features": "LED Display, Voltage Monitor, Independent Switch, Universal for Cars, Dual USB",
    "dim": "40 x 50 x 120mm",
    "weight": "125.0 g",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "🔌 2-in-1 Power Hub:​ Combines 2 cigarette lighter sockets and 2 USB-A ports, expanding your car’s power supply.\n⚡ 120W High Power:​ Delivers up to 120W total output, with 80W dedicated to the sockets for high-power car accessories.\n🛡️ Safe & Smart:​ Built with fireproof PC+ABS, comprehensive safety protections, and a car battery voltage LED display.",
    "desc": "Product Name: ZNB02  2-Socket Cigarette Lighter Splitter with 2-Port USB Car Charger(2A)\nPower Input Voltage: DC 12V-24V\nTotal Output Power: Max 120W\nOutput Port(s): 2 USB-A + 2 Cigarette Sockets\nUSB-A1 Output: 5V/3A, 9V/2A, 12V/1.5A (QC3.0 18W)\nUSB-A2 Output: 5V/3.1A\n\n2 Sockets Extension Output: 80W Max\n\nDesign Material: Fireproof PC + ABS\nSafety Protections: OCP, OVP, OTP, Short Circuit Protection\nCertifications: CE, FCC, RoHS\nOthers Features: Car Battery Voltage LED Display",
    "p_sample": "39.0",
    "p_500": "38.0",
    "p_2000": "36.0",
    "p_5000": "35.0",
    "acc": "User Manual x1",
    "product_dim": "40 x 50 x 120mm",
    "box_dim": "48 x 86 x 130mm",
    "carton_dim": "47 x 35 x 38cm",
    "qty_carton": "100pcs/carton",
    "product_nw": "125.0 g",
    "box_gw": "165.0 g",
    "carton_gw": "",
    "year": ""
  },
  {
    "model": "ZNB03S",
    "category": "Car Charger",
    "type_cn": "一拖三点烟器",
    "type_en": "Smart USB Car Charger",
    "image": "images/ZNB03S.jpg",
    "power": "Total 120W",
    "ports": "2x USB-A",
    "features": "Voltage Monitor, Independent Switch, Universal for Cars, Dual USB",
    "dim": "96 x 32 x 69mm",
    "weight": "131.0 g",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "color": "Black",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "🔌 3-in-1 Power Hub:​ Converts one cigarette lighter socket into 3 sockets and 2 USB-A ports.\n⚡ 120W High Power:​ Supports up to 120W total output for high-power car accessories.\n🛡️ Safe & Reliable:​ Built with fireproof PC+ABS and comprehensive safety protections.",
    "desc": "1-to-3 Car Charger\nVoltage Range: 6-30V\nInput Voltage: 12V-24V\nTotal Output Power: 120W\nOutput Ports: 2\nUSB 1 Output: 5V/1A\nUSB 2 Output: 5V/2.1A\nProduct Material: Plastic\nIndependent Switch Control\nPower Cable Length: 100cm\n3Cigarette Lighter Sockets\nCertification: CE FCC RoHS Design Patent",
    "p_sample": "17.0",
    "p_500": "16.0",
    "p_2000": "15.0",
    "p_5000": "14.0",
    "acc": "1. User Manual x1\n2. Fuse x1\n3. 3M Sticker x1",
    "product_dim": "96 x 32 x 69mm",
    "box_dim": "153 x 40 x 114mm",
    "carton_dim": "46.5 x 34 x 31cm",
    "qty_carton": "50pcs/carton",
    "product_nw": "131.0 g",
    "box_gw": "175.0 g",
    "carton_gw": "",
    "year": ""
  },
  {
    "model": "GR01",
    "category": "Bluetooth Receiver",
    "type_cn": "蓝牙接收器",
    "type_en": "Bluetooth Receiver",
    "image": "images/GR01-alt.jpg",
    "bt": "BT 5.4",
    "ports": "3.5mm AUX, TF Card Slot",
    "features": "Colorful Lights, TF Card Slot, Stereo, Smart Chip, Multi-point, Noise Reduction",
    "signal": "50 m",
    "dim": "90 x 21 x 128 mm",
    "weight": "42.4 g",
    "input_v": "DC 5V",
    "color": "Black",
    "cert": "CE, FCC, RoHS",
    "audio": "SBC, AAC",
    "rxtx": "RX",
    "selling": "📡 50m Ultra-Long Range:​ Equipped with an external flexible antenna for a stable connection up to 50m in open space.\n💾 Built-in Media Player:​ Supports direct playback from a TF (microSD) card, eliminating the need for a phone.\n🎶 Ambient Lighting & Microphone:​ Features built-in ambient lighting and a microphone with a 1.0m effective range for calls.",
    "desc": "Product Name: GR01 Ultra-Long Range Bluetooth Receiver\nBluetooth Version: 5.4\n\nBluetooth Profiles: A2DP, AVRCP, HFP/HSP\nAudio Codecs: SBC, AAC\nWireless Frequency: 2.4 GHz (2402–2480 MHz)\nAntenna: 1 × External Flexible Antenna\n\nWireless Range: Up to 50m (open space, line-of-sight)\nMicrophone Effective Distance: 0–1.0m\n\nWorking Voltage: DC 5V\nPower Consumption: ≤0.325W (Max)\nUSB-C Input: 5V / 65mA (Max)\n\n3.5mm Aux Output: 1 × 3.5mm Stereo Jack\nTF (microSD) Card Slot: 1 × Slot, supports up to 32GB\nSupported Audio Formats: MP3, WMA\nOperating Temperature: 0°C – 45°C\nCertifications: CE, FCC, RoHS\nOther Features: Built-in ambient lighting & TF (microSD) Card Playback",
    "p_sample": "27.0",
    "p_500": "26.0",
    "p_2000": "25.0",
    "p_5000": "24.0",
    "acc": "User Manual, 3.5mm Audio Cable, USB Charging Cable",
    "proto": "A2DP, AVRCP, HFP/HSP",
    "product_nw": "42.4 g",
    "box_gw": "86.4 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GR03",
    "category": "Bluetooth Receiver",
    "type_cn": "蓝牙接收器",
    "type_en": "Bluetooth Receiver",
    "image": "images/GR03-alt.jpg",
    "bt": "BT 5.4",
    "ports": "3.5mm AUX, TF Card Slot",
    "features": "TF Card Slot, Stereo, Smart Chip, Multi-point, Leather Texture, Long Battery Life, Power Display",
    "battery": "250mAh",
    "signal": "10 m",
    "dim": "90 x 21 x 128 mm",
    "weight": "16.5 g",
    "input_v": "DC 5V",
    "cert": "CE, FCC, RoHS",
    "audio": "SBC, AAC",
    "rxtx": "RX",
    "selling": "🔋 Rechargeable & Portable:​ Built-in 250mAh battery offers up to 16 hours of standby time.\n💾 Direct TF Card Playback:​ Play music directly from a microSD card without needing a phone.\n🌈 RGB Lighting:​ Features built-in RGB lighting for a stylish appearance.",
    "desc": "Product Name: GR03 Mini Rechargeable Bluetooth Receiver\nBluetooth Version: 5.4\nBluetooth Profiles: A2DP, AVRCP, HFP/HSP\nAudio Codecs: SBC, AAC\n\nWireless Range: 10m (open space, line-of-sight)\nMicrophone Effective Distance: 0–1.0m\n\nWorking Voltage: DC 5V\n\nUSB-C Input: 5V / 30mA (Max)\n\n3.5mm Aux Output: 1 × 3.5mm Stereo Jack\nTF (microSD) Card Slot: 1 × Slot, supports up to 32GB\nSupported Audio Formats: MP3, WMA\nOperating Temperature: 0°C – 45°C\n\nBattery Capacity: Built-in 250mAh rechargeable lithium battery\nStandby Time: Up to 16 hours\nCharging Time: Approx. 2 hours\n\nCertifications: CE, FCC, RoHS\nOther Features: Built-in RGB lighting & TF (microSD) Card Playback",
    "p_sample": "22.0",
    "p_500": "21.0",
    "p_2000": "20.0",
    "p_5000": "19.0",
    "acc": "User Manual, 3.5mm Audio Cable, USB Charging Cable",
    "proto": "A2DP, AVRCP, HFP/HSP",
    "product_nw": "16.5 g",
    "box_gw": "35.0 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GR07",
    "category": "Bluetooth Receiver",
    "type_cn": "蓝牙接收器",
    "type_en": "Bluetooth Receiver",
    "image": "images/GR07-alt.jpg",
    "bt": "BT 5.4",
    "ports": "3.5mm AUX, TF Card Slot",
    "features": "Colorful Lights, TF Card Slot, Stereo, Smart Chip, Long Battery Life",
    "battery": "250mAh",
    "signal": "10 m",
    "dim": "90 x 21 x 128 mm",
    "weight": "28.0 g",
    "input_v": "DC 5V",
    "color": "Black",
    "cert": "CE, FCC, RoHS",
    "audio": "SBC, AAC",
    "rxtx": "RX",
    "selling": "🌈 Built-in RGB Lighting​ – Adds stylish visual effect while in use.\n💾 TF Card Playback​ – Plays music directly from a microSD card without a phone.\n🔋 Rechargeable Battery​ – 250mAh battery with up to 16 hours of standby time.",
    "desc": "Product Name: GR07 RGB Light Bluetooth Receiver\nBluetooth Version: 5.4\nBluetooth Profiles: A2DP, AVRCP, HFP/HSP\nAudio Codecs: SBC, AAC\n\nWireless Range: 10m (open space, line-of-sight)\nMicrophone Effective Distance: 0–1.0m\n\nWorking Voltage: DC 5V\n\nUSB-C Input: 5V / 30mA (Max)\n\n3.5mm Aux Output: 1 × 3.5mm Stereo Jack\nTF (microSD) Card Slot: 1 × Slot, supports up to 32GB\nSupported Audio Formats: MP3, WMA\nOperating Temperature: 0°C – 45°C\n\nBattery Capacity: Built-in 250mAh rechargeable lithium battery\nStandby Time: Up to 16 hours\nCharging Time: Approx. 2 hours\n\nCertifications: CE, FCC, RoHS\nOther Features: Built-in RGB lighting & TF (microSD) Card Playback",
    "p_sample": "3.15",
    "p_500": "21.0",
    "p_2000": "20.0",
    "p_5000": "19.0",
    "acc": "User Manual, 3.5mm Audio Cable, USB Charging Cable",
    "proto": "A2DP, AVRCP, HFP/HSP",
    "product_nw": "28.0 g",
    "box_gw": "52.0 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GR08",
    "category": "Bluetooth Receiver",
    "type_cn": "蓝牙接收器",
    "type_en": "Bluetooth Receiver",
    "image": "images/GR08.jpg",
    "bt": "BT 6.0",
    "chip": "JieLi (杰理)",
    "features": "Multi-point",
    "signal": "10M",
    "dim": "70 x 21 x 128 mm",
    "weight": "25.0 g",
    "cable": "1.5m",
    "p_2000": "10.0",
    "p_5000": "8.0",
    "acc": "User Manual, 3.5mm Audio Cable",
    "proto": "SBC, A2DP, HFP, HSP",
    "p_sample": "12.0",
    "p_500": "11.0",
    "product_nw": "25.0 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GR11",
    "category": "Bluetooth Receiver",
    "type_cn": "蓝牙接收发射二合一",
    "type_en": "BT Audio RX/TX 2-in-1",
    "image": "images/GR11-alt.jpg",
    "bt": "BT 5.4",
    "chip": "JieLi (杰理)",
    "ports": "Type-C",
    "features": "Stereo, Multi-point, Noise Reduction, Aluminum Body, Metal Body",
    "battery": "250mAh",
    "signal": "10M",
    "dim": "90 x 24 x 129 mm",
    "weight": "30.7 g",
    "input_v": "DC 5V",
    "rxtx": "RX + TX",
    "p_sample": null,
    "p_500": null,
    "p_2000": null,
    "p_5000": null,
    "acc": "User Manual, 3.5mm Audio Cable, USB Charging Cable",
    "proto": "SBC, A2DP, HFP, HSP, AVRCP",
    "product_nw": "30.7 g",
    "box_gw": "64.5 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GR13",
    "category": "Bluetooth Receiver",
    "type_cn": "蓝牙接收器",
    "type_en": "Bluetooth Receiver",
    "image": "images/GR13.jpg",
    "bt": "BT 5.4",
    "ports": "3.5mm AUX, TF Card Slot",
    "features": "TF Card Slot, Stereo, Smart Chip, Multi-point, Metal Body, Long Battery Life",
    "battery": "250mAh",
    "signal": "10 m",
    "dim": "90 x 21 x 128 mm",
    "weight": "28.0 g",
    "input_v": "DC 5V",
    "color": "Black",
    "cert": "CE, FCC, RoHS",
    "audio": "SBC, AAC",
    "rxtx": "RX",
    "selling": "🔋 Rechargeable Mini Design​ – Compact size with built-in 250mAh battery for up to 20h standby.\n💾 TF Card Playback​ – Play music directly from a microSD card without a phone.\n🎧 3.5mm Aux Output​ – Easy connection to car stereos, speakers, or headphones.",
    "desc": "Product Name: GR13 Mini Rechargeable Bluetooth Receiver\nBluetooth Version: 5.4\nBluetooth Profiles: A2DP, AVRCP, HFP/HSP\nAudio Codecs: SBC, AAC\n\nWireless Range: 10m (open space, line-of-sight)\nMicrophone Effective Distance: 0–1.0m\n\nWorking Voltage: DC 5V\n\nUSB-C Input: 5V / 30mA (Max)\n\n3.5mm Aux Output: 1 × 3.5mm Stereo Jack\nTF (microSD) Card Slot: 1 × Slot, supports up to 32GB\nSupported Audio Formats: MP3, WMA\nOperating Temperature: 0°C – 45°C\n\nBattery Capacity: Built-in 250mAh rechargeable lithium battery\nStandby Time: Up to 20 hours\nCharging Time: Approx. 2 hours\n\nCertifications: CE, FCC, RoHS\nOther Features: TF (microSD) Card Playback",
    "p_sample": "24.0",
    "p_500": "23.0",
    "p_2000": "22.0",
    "p_5000": "21.0",
    "acc": "User Manual, 3.5mm Audio Cable, USB Charging Cable",
    "proto": "A2DP, AVRCP, HFP/HSP",
    "product_nw": "28.0 g",
    "box_gw": "52.0 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GR15",
    "category": "Bluetooth Receiver",
    "type_cn": "蓝牙接收发射器",
    "type_en": "Bluetooth Transceiver",
    "image": "images/GR15.jpg",
    "bt": "BT 5.4",
    "chip": "Qualcomm (高通)",
    "ports": "3.5mm AUX, Optical",
    "battery": "450mAh",
    "signal": "10 m",
    "dim": "122 x 24 x 97 mm",
    "weight": "106.8g",
    "input_v": "DC 5V",
    "cert": "CE, FCC, RoHS",
    "audio": "SBC, AAC, aptX HD, aptX LL, aptX Adaptive",
    "rxtx": "RX/TX",
    "selling": "📡 Dual Antenna & Qualcomm 5.4​ – Enhanced signal stability and support for aptX HD/LL/Adaptive codecs.\n🔀 3-in-1 Functionality​ – Works as Bluetooth TX, RX, and a dual optical bypass for lossless pass-through.\n🎧 Multi-Interface Support​ – Includes 2× 3.5mm AUX and 2× optical ports for flexible audio connections.",
    "desc": "Product Name: GR15 Dual Antenna  3-in-1 Bluetooth Receiver & Transmitter & Dual Optical Bypass\nBluetooth Version: 5.4 (Qualcomm chipset)\nBluetooth Profiles: A2DP, AVRCP, HFP/HSP\nAudio Codecs: SBC, AAC, aptX HD, aptX LL, aptX Adaptive\n\nInterfaces:\n- 2 x 3.5mm AUX (Input/Output)\n- 2 x Optical (TX Input / RX Output)\n- USB-C (for charging)\nWorking Modes: \n-Bypass: Dual Optical (optical in to optical out, physical layer pass-through)\n-TX (Transmitter) / RX (Receiver) dual mode, both supporting 1-to-2 simultaneous Bluetooth connections\nWireless Range: 10m (open space, line-of-sight)\nSupported Audio Formats: MP3, WMA\n\nBattery Capacity: Built-in 450mAh rechargeable lithium battery\nBattery Life\nRX Mode Standby Time: up to 15hrs\nTX Mode Standby Time: up to 16hrs\nCharging Time: Approx. 2 hours\nWorking Voltage: DC 5V\nUSB-C Input: 5V / 1A (Max)\n\nCertifications: CE, FCC, RoHS",
    "proto": "A2DP, AVRCP, HFP/HSP",
    "p_sample": "90.0",
    "p_500": "90.0",
    "p_2000": "85.0",
    "p_5000": "80.0",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GR16",
    "category": "Bluetooth Receiver",
    "type_cn": "蓝牙接收发射器",
    "type_en": "Bluetooth Transceiver",
    "image": "images/GR16.jpg",
    "bt": "BT 5.4",
    "ports": "3.5mm AUX",
    "features": "Multi-point, Dual Connection, Aluminum Body",
    "battery": "300mAh",
    "signal": "10 m",
    "dim": "51 x 49 x 17 mm",
    "input_v": "DC 5V",
    "cert": "CE, FCC, RoHS",
    "audio": "SBC, AAC",
    "rxtx": "RX/TX",
    "selling": "💡 Dual 3.5mm AUX for Air Travel​ – Designed specifically for airplane seat audio systems.\n🔄 2-in-1 TX/RX Mode​ – Supports simultaneous 1-to-2 Bluetooth connections in both modes.\n🔋 Rechargeable Battery​ – 300mAh battery with up to 16h RX or 13h TX standby time.\n🌈 Built-in RGB lighting (can be turned off)",
    "desc": "GR16 2-in-1 Bluetooth Transmitter & Receiver with Dual 3.5mm AUX for Air Travel\nBluetooth Version: 5.4 \nBluetooth Profiles: A2DP, AVRCP, HFP/HSP\nAudio Codecs: SBC, AAC\n\nInterfaces: Dual 3.5mm Aux Plug (for Air travel), USB-C (for charging)\nWorking Modes: TX (Transmitter) / RX (Receiver) dual mode, both supporting 1-to-2 simultaneous Bluetooth connections\nWireless Range: 10m (open space, line-of-sight)\nSupported Audio Formats: MP3, WMA\n\nBattery Capacity: Built-in 300mAh rechargeable lithium battery\nBattery Life\nRX Mode Standby Time: up to 16hrs\nTX Mode Standby Time: up to 13hrs\nCharging Time: Approx. 2 hours\nWorking Voltage: DC 5V\nUSB-C Input: 5V / 1A (Max)\n\nCertifications: CE, FCC, RoHS\nOther Features: Built-in RGB lighting (can be turned off)",
    "proto": "A2DP, AVRCP, HFP/HSP",
    "p_sample": "38.0",
    "p_500": "37.0",
    "p_2000": "36.0",
    "p_5000": "35.0",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GR18",
    "category": "Bluetooth Receiver",
    "type_cn": "蓝牙接收发射器",
    "type_en": "Bluetooth Transceiver",
    "image": "images/GR18.jpg",
    "bt": "BT 5.4",
    "ports": "3.5mm AUX",
    "features": "TF Card Slot, Multi-point, Dual Connection",
    "battery": "300mAh",
    "signal": "10 m",
    "input_v": "DC 5V",
    "cert": "CE, FCC, RoHS",
    "audio": "SBC, AAC",
    "rxtx": "RX/TX",
    "desc": "GR18 2-in-1 Bluetooth Transmitter & Receiver\nBluetooth Version: 5.4\nBluetooth Profiles: A2DP, AVRCP, HFP/HSP\nAudio Codecs: SBC, AAC\n\nInterfaces: 3.5mm Aux Jack (for audio in/out), USB-C (for charging)\nWorking Modes: TX (Transmitter) / RX (Receiver) dual mode, both supporting 1-to-2 simultaneous Bluetooth connections\nWireless Range: 10m (open space, line-of-sight)\nSupported Audio Formats: MP3, WMA\n\nBattery Capacity: Built-in 300mAh rechargeable lithium battery\nBattery Life\nRX Mode Standby Time: up to 15hrs\nTX Mode Standby Time: up to 11hrs\nCharging Time: Approx. 2 hours\nWorking Voltage: DC 5V\nUSB-C Input: 5V / 1A (Max)\n\nCertifications: CE, FCC, RoHS\nOther Features:",
    "proto": "A2DP, AVRCP, HFP/HSP",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GR31",
    "category": "Bluetooth Receiver",
    "type_cn": "蓝牙接收器",
    "image": "images/GR31.jpg",
    "bt": "BT 5.3",
    "features": "Stereo, Multi-point",
    "signal": "10M",
    "dim": "70 x 21 x 128 mm",
    "cable": "1.7m",
    "proto": "SBC, A2DP, HFP, HSP, AVRCP",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GZ01",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/GZ01.jpg",
    "bt": "BT 5.3",
    "ports": "2x USB-A, 1x USB-C",
    "features": "Colorful Lights, 7 Color Modes, Stereo, Universal for Cars, Smart Chip, Power-off Memory",
    "signal": "10-15 m",
    "dim": "70.5 x 46 x 98 mm",
    "weight": "29.8 g",
    "fm": "87.5-108.0 MHz",
    "color": "Black",
    "selling": "⚡️ Charge 3 Devices at Once with 2A1C Turbo Power\n💡 Smart Ambient Lighting\n📊 Shows FM + Battery Voltage simultaneously\nBonus: Bluetooth 5.3 (10m) + TF/USB/FM playback",
    "desc": "Product Name: GZ01 Car FM Transmitter\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nLED Display: FM/Car battery Voltage display\nTransmission Distance: 10-15m\nOutput ports: 3\nUSB-A1 output: 5V/1A(Supports u-disk media playback)\nUSB-A2 output: 5V/3.0A\nUSB-C1 output: 5V/3.0A\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters\nOthers Features: Built-in ambient lighting",
    "p_sample": "26.0",
    "p_500": "25.0",
    "p_2000": "24.0",
    "p_5000": "23.0",
    "acc": "User Manual",
    "product_nw": "29.8 g",
    "box_gw": "54.0 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GZ03",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/GZ03.jpg",
    "bt": "BT 5.3",
    "ports": "2x USB-A, 1x USB-C",
    "features": "Heavy Bass, Lossless Sound, HD Mic, Fast Charge, Voice Navigation, U Disk Play, Stereo, Universal for Cars, FM Transmit",
    "signal": "10-15 m",
    "dim": "70.5 x 46 x 98 mm",
    "weight": "29.8 g",
    "fm": "87.5-108.0 MHz",
    "input_v": "12V/24V DC",
    "color": "Black",
    "selling": "⚡️ Charge 3 Devices at Once with 2A1C Turbo Power\n💡 Smart Ambient Lighting\n📊 Shows FM + Battery Voltage simultaneously\nBonus: Bluetooth 5.3 (10m) + TF/USB/FM playback",
    "desc": "Product Name: GZ03 Car FM Transmitter\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nLED Display: FM/Car battery Voltage display\nTransmission Distance: 10-15m\nOutput ports: 3\nUSB-A1 output: 5V/1A(Supports u-disk media playback)\nUSB-A2 output: 5V/3.0A\nUSB-C1 output: 5V/3.0A\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters\nOthers Features: Built-in ambient lighting",
    "p_sample": "19.0",
    "p_500": "18.0",
    "p_2000": "17.0",
    "p_5000": "16.0",
    "acc": "User Manual",
    "product_nw": "29.8 g",
    "box_gw": "54.0 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GZ03-PD",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/GZ03.jpg",
    "bt": "BT 5.4",
    "ports": "PD",
    "features": "Heavy Bass, Lossless Sound, HD Mic, Fast Charge, Voice Navigation, U Disk Play, Stereo, Universal for Cars, FM Transmit",
    "signal": "10-15 m",
    "dim": "70.5 x 46 x 98 mm",
    "weight": "29.8 g",
    "fm": "87.5-108.0 MHz",
    "input_v": "12V/24V DC",
    "color": "Black",
    "selling": "⚡️ Charge 3 Devices at Once with 2A1C Turbo Power\n💡 Smart Ambient Lighting\n📊 Shows FM + Battery Voltage simultaneously\nBonus: Bluetooth 5.3 (10m) + TF/USB/FM playback",
    "desc": "Product Name: GZ03 Car FM Transmitter\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nLED Display: FM/Car battery Voltage display\nTransmission Distance: 10-15m\nOutput ports: 3\nUSB-A1 output: 5V/1A(Supports u-disk media playback)\nUSB-A2 output: 5V/3.0A\nUSB-C1 output: 5V/3.0A\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters\nOthers Features: Built-in ambient lighting",
    "p_sample": "19.0",
    "p_500": "18.0",
    "p_2000": "17.0",
    "p_5000": "16.0",
    "acc": "User Manual",
    "power": "PD 5V/3.0A, 9V/3.0A, 12V/2.5A •  USB-A Output Port: 5V/2.4A •   | USB-A 5V/2.4A",
    "product_nw": "29.8 g",
    "box_gw": "54.0 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GZ07",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/GZ07.jpg",
    "bt": "BT 5.3",
    "ports": "1x USB-A, 2x USB-C",
    "features": "Heavy Bass, Lossless Sound, HD Mic, Fast Charge, Voice Navigation, U Disk Play, Stereo, Universal for Cars, FM Transmit",
    "signal": "10-15 m",
    "dim": "70.5 x 46 x 98 mm",
    "fm": "87.5-108.0 MHz",
    "input_v": "12V/24V DC",
    "selling": "⚡️ Charge 3 Devices at Once with 2A1C Turbo Power\n💡 Smart Ambient Lighting\n📊 Shows FM + Battery Voltage simultaneously\nBonus: Bluetooth 5.3 (10m) + TF/USB/FM playback",
    "desc": "Product Name: GZ07 Car FM Transmitter\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nLED Display: FM/Car battery Voltage display\nTransmission Distance: 10-15m\nOutput ports: 3\nUSB-A1 output: 5V/1A(Supports u-disk media playback)\nUSB-C1 output: 5V/3.0A\nUSB-C2 output: 5V/3.0A\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters\nOthers Features: Built-in ambient lighting\nOne-click bass boost",
    "p_sample": "18.0",
    "p_500": "17.0",
    "p_2000": "16.0",
    "p_5000": "15.0",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GZ08-DualPD35W",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/GZ08-DualPD35W.png",
    "bt": "BT 5.3",
    "power": "PD 35W",
    "ports": "1x USB-A, 2x USB-C",
    "features": "Colorful Lights, Heavy Bass, Lossless Sound, HD Mic, Fast Charge, Voice Navigation, U Disk Play, Stereo, Universal for Cars, FM Transmit",
    "signal": "10-15 m",
    "dim": "70.5 x 46 x 98 mm",
    "weight": "36.0 g",
    "fm": "87.5-108.0 MHz",
    "input_v": "12V/24V DC",
    "selling": "🌟 Dual USB-C 3A Fast Charging​ - Power 2 devices at full speed simultaneously\n🎵 One-Click Bass Boost​ - Instantly enhance audio depth\n💡 Smart Ambient Lighting​ - Functional mood lighting + voltage display\nBonus: Bluetooth 5.3 + FM/USB/TF multi-playback",
    "desc": "Product Name: GZ08 Car FM Transmitter with One-click Bass Boost\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nLED Display: FM/Car battery Voltage display\nTransmission Distance: 10-15m\nOutput ports: 3\nUSB-A1 output: 5V/1A(Supports u-disk media playback)\nUSB-C1 output: 5V/3.0A\nUSB-C2 output: 5V/3.0A\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters\nOthers Features: Built-in ambient lighting\nOne-click bass boost",
    "acc": "User Manual",
    "product_nw": "36.0 g",
    "box_gw": "65.0 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "p_sample": "25.0",
    "p_500": "24.0",
    "p_2000": "23.0",
    "p_5000": "22.0",
    "year": ""
  },
  {
    "model": "GZ11",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/GZ11.jpg",
    "bt": "BT 5.3",
    "ports": "2x USB-A, Retractable Cable",
    "features": "Colorful Lights, Lossless Sound, HD Mic, Voice Navigation, U Disk Play, Stereo, Universal for Cars, FM Transmit",
    "signal": "10-15 m",
    "dim": "75 x 54 x 115 mm",
    "fm": "87.5-108.0 MHz",
    "input_v": "12V/24V DC",
    "selling": "⚡ 65W Retractable PD Cable​ - Full laptop & Smartphone charging (20V/3.25A)\n🔌 Dual High-Power Outputs​ - 3A USB-A + 65W USB-C simultaneously\n🎛️ Smart Combo​ - Bass boost + ambient lighting + voltage display\nBonus: Self-retracting 78cm cable + Bluetooth 5.3",
    "desc": "Product Name: GZ11 Car FM Transmitter with PD 65W retractable cable\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nLED Display: FM/Car battery Voltage display\nTransmission Distance: 10-15m\nOutput ports: 3\nUSB-A1 output: 5V/1A(Supports u-disk media playback)\nUSB-A2 output: 5V/3.0A\nRetractable Charging USB-C Cable output: 5V/3A, 9V/3A, 12V/3A, 15V/3A, 20V/3.25A (Max 65w)\n15v and 20v outputs are only available on 24v vehicles \nRetractable Calbe Length: Max 78cm ±1cm\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters\nOthers Features: Built-in ambient lighting\nOne-click bass boost",
    "p_sample": "45.0",
    "p_500": "44.0",
    "p_2000": "43.0",
    "p_5000": "42.0",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GZ11-C",
    "category": "Car Charger",
    "type_cn": "车载充电器",
    "type_en": "Car Charger",
    "image": "images/GZ11-C.jpg",
    "power": "Total 65W",
    "ports": "1x USB-A, 3x USB-C, Retractable Cable",
    "features": "Colorful Lights, Smart Protection, Universal for Cars, Flame-retardant",
    "dim": "68.8 x 50.5 x 98mm",
    "cable": "78cm",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "🔌 Built-in 65W PD retractable cable\n⚡  83W total output (65W+18W) with 1A3C ports\n🛡 Safe with fireproof PC+ABS and ambient lighting",
    "desc": "Smart Retractable Cable Design, Dual Independent Circuits\nInput Voltage: DC 12V-24V / 5A Max\nTotal Output Power: 65W+18W\nPD Retractable Cable Output: 5V/3.0A,9V/3.0A,12V/3.0A,15V/3.0A,20V/3.25A(limited to 24V vehicles, e.g. trucks, buses, Max Power 65W 15V/20V)\nUSB-A + USB-C1 + USB-C2 Output: 5V/3.6A(18W)\nMaterial: Flame-Retardant PC+ABS\nPD Cable Length: 78cm(Retractable)\nWorking Temperature: -20℃~60℃",
    "p_sample": "40.0",
    "p_500": "39.0",
    "p_2000": "36.0",
    "p_5000": "35.0",
    "acc": "User Manual x1",
    "product_dim": "68.8 x 50.5 x 98mm",
    "box_dim": "75 x 54 x 115mm",
    "carton_dim": "57 x 25 x 39.5cm",
    "qty_carton": "100pcs/carton",
    "product_nw": "72.2g",
    "box_gw": "104g",
    "carton_gw": "",
    "year": ""
  },
  {
    "model": "AP06",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/AP06.jpg",
    "bt": "BT 5.3",
    "ports": "2x USB-A, 3.5mm AUX, TF Card Slot",
    "features": "7 Color Modes, Lossless Sound, HD Sound, Voice Assistant, One Key Answer, Hands-free Call, TF Card Slot",
    "signal": "10-15 m",
    "dim": "62 x 45.5 x 110.5 mm",
    "weight": "90.0 g",
    "fm": "87.5-108.0 MHz",
    "material": "Zinc Alloy Body",
    "color": "Silver",
    "selling": "🌈Military-Grade Zinc Alloy Body​ - Ultra durable construction\n 🔥Built-in Emergency Hammer​ - Quick window break in emergencies\n ✅ Bluetooth 5.3​ - 10m stable wireless connection",
    "desc": "Product Name: AP06 Car FM Transmitter with Emergency Hammer\nMaterial: Zinc Alloy Body\nEmergency Function: Built-in Window-Breaking Hammer\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nTransmission Distance: 10-15m\nOutput ports: 2\nUSB-A1 output: 5V/1A(Supports u-disk media playback)\nUSB-A2 output: 5V/2.1A\nTF card Slot: 1\n3.5mm Aux Output Port: 1\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters",
    "p_sample": "53.0",
    "p_500": "52.0",
    "p_2000": "51.0",
    "p_5000": "50.0",
    "acc": "User Manual, 3.5mm Audio Cable",
    "product_nw": "90.0 g",
    "box_gw": "130.0 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "M7",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/M7.jpg",
    "bt": "BT 5.3",
    "ports": "3x USB-A, 3.5mm AUX, TF Card Slot",
    "features": "Lossless Sound, HD Mic, Fast Charge, One Key Answer, Hands-free Call, TF Card Slot, U Disk Play, Universal for Cars",
    "signal": "10-15 m",
    "dim": "72.5 x 71 x 179 mm",
    "fm": "87.5-108.0 MHz",
    "input_v": "12V/24V DC",
    "color": "Black",
    "selling": "📺 LCD Screen Display​ - Clear visual interface for easy control\n🔌 Triple USB Charging Ports​ - Charge 3 devices simultaneously\n🎵 Versatile Playback Options​ - USB/TF/AUX/Bluetooth/FM all-in-one\nBonus: Bluetooth 5.3 stable connection (10m range)",
    "desc": "Product Name: M7 Car FM Transmitter with LCD Screen\nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nTransmission Distance: 10-15m\nOutput ports: 3\nUSB-A1 output: 5V/1A(Supports u-disk media playback)\nUSB-A2 output: 5V/2.1A\nUSB-A3 output: 5V/2.1A\nTF card Slot: 1\n3.5mm Aux Output Port: 1\nMusic Format: MP3/WMA\nFM frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters",
    "proto": "A2DP",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GC07",
    "category": "Car Charger",
    "type_cn": "车载充电器",
    "type_en": "Car Charger",
    "image": "images/GC07.jpg",
    "power": "Total 61W",
    "ports": "2x USB-A",
    "dim": "28 x 67.6mm",
    "weight": "19.0 g",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "selling": "🔌 Dual-Port 2.4A Output​ - Charge two devices simultaneously at 2.4A each.\n🔋 Wide 12V-24V Input​ - Compatible with both cars and trucks.\n🛡️ Safe & Certified​ - Built with fireproof PC+ABS and CE/FCC/RoHS certifications.",
    "desc": "Input: 12V-24V\nOutput Ports: 2\nUSB 1 Output: 5V/2.4A\nUSB 2 Output: 5V/2.4A\nMaterial: ABS\nColor: Black + Gray\nCertification: CE FCC RoHS Design Patent",
    "acc": "OEM Only,MOQ: 2000pcs",
    "product_dim": "28 x 67.6mm",
    "product_nw": "19.0 g",
    "carton_gw": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "p_sample": "20.0",
    "p_500": "19.0",
    "p_2000": "18.0",
    "p_5000": "17.5",
    "year": ""
  },
  {
    "model": "GR05",
    "category": "Bluetooth Receiver",
    "type_cn": "蓝牙接收发射器",
    "type_en": "Bluetooth Transceiver",
    "image": "images/GR05-LED.jpg",
    "bt": "BT 5.3",
    "battery": "250mAh",
    "signal": "10 m",
    "dim": "70 x 30 x 15 mm",
    "weight": "21.5 g",
    "input_v": "DC 5V",
    "rxtx": "RX/TX",
    "p_sample": "38.0",
    "p_500": "37.0",
    "p_2000": "36.0",
    "p_5000": "35.0",
    "acc": "User Manual, 3.5mm Audio Cable, USB Charging Cable",
    "product_nw": "21.5 g",
    "box_gw": "60.0 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GR05-Wired-JL",
    "category": "Bluetooth Receiver",
    "type_cn": "蓝牙接收发射器",
    "type_en": "Bluetooth Transceiver",
    "image": "images/GR05-LED.jpg",
    "bt": "BT 5.4",
    "battery": "300mAh",
    "signal": "10 m",
    "dim": "70 x 30 x 15 mm",
    "weight": "21.5 g",
    "input_v": "DC 5V",
    "rxtx": "RX/TX",
    "p_sample": "38.0",
    "p_500": "37.0",
    "p_2000": "36.0",
    "p_5000": "35.0",
    "acc": "User Manual, 3.5mm Audio Cable, USB Charging Cable",
    "ports": "Type-C",
    "features": "TF Card Slot, Stereo, Smart Chip, Bendable Plug, Long Battery Life",
    "product_nw": "21.5 g",
    "box_gw": "60.0 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "G21",
    "category": "Car Bluetooth MP3",
    "type_cn": "车载FM发射器",
    "type_en": "Car FM Transmitter",
    "image": "images/G21.jpg",
    "bt": "BT 5.3",
    "ports": "3x USB-A, 3.5mm AUX, TF Card Slot",
    "signal": "10-15 m",
    "selling": "📻 DAB+FM Dual Band​ (174-240MHz + 87.5-108MHz) - Enhanced radio coverage\n🔥 LED Screen Display​ - Clear visual interface\n🚀 QC3.0 18W Fast Charging​ - Ultra-fast power delivery",
    "desc": "Product Name: G21 Car FM Transmitter with LED Screen & \nBluetooth Version: V5.3\nWorking Voltage: 12V-24V\nLimit Voltage: 9-26V\nTransmission Distance: 10-15m\nOutput ports: 3\nUSB-A1 output: 5V/1A(Supports u-disk media playback)\nUSB-A2 output: 5V/2.1A\nUSB-A3 output: QC3.0 18W\nTF card Slot: 1\n3.5mm Aux Input Port: 1\n3.5mm Aux Output Port: 1\nMusic Format: MP3/WMA\nFrequency Range: DAB Band III (174-240MHz); FM 87.5-108MHz\nMicrophone Effective Distance: 0-1.0 meters\nBluetooth Effective Distance: 10 meters\nFM Effective Distance: 2-3 meters",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "G63",
    "category": "Car Charger",
    "type_cn": "车载FM发射器",
    "type_en": "Car FM Transmitter",
    "image": "images/G63-Standard.jpg",
    "bt": "BT 5.3",
    "ports": "TF Card Slot",
    "signal": "10-15 m",
    "fm": "87.5-108.0 MHz",
    "selling": "🔌 Dual Cigarette Sockets​ - Power 2 devices simultaneously\n🎛 Wireless Steering Wheel Remote​ - Control music without touching device\n🔋 3A USB-C Fast Charging​ - Ultra-fast power delivery\nBonus: Bluetooth 5.3 + Battery voltage monitoring",
    "desc": "Bluetooth Version: V5.3\nWorking Voltage: 12V-24V\nVoltage Limit: 9-26V\nTransmission Distance: 10-15m\nOutput Ports: 2\nUSB Output: 5V/1A(Read USB Drive for Music Playback)\nType-C Output: PD 25W\n2-Port Power: 80W\nTF Card Slot: 1\nFM Frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0m\nBluetooth Effective Range: 10m\nFM Effective Range: 2-3m\n2Cigarette Lighter Sockets\nCertification: CE FCC RoHS Design Patent",
    "dim": "85 x 75 x 60mm",
    "acc": "User Manual x1",
    "product_dim": "85 x 75 x 60mm",
    "box_dim": "108 x 165 x 85mm",
    "carton_dim": "44.5 x 34 x 56cm",
    "qty_carton": "50pcs/carton",
    "product_nw": "133.8g",
    "box_gw": "215.9g",
    "carton_gw": "",
    "p_sample": "43.0",
    "p_500": "42.0",
    "p_2000": "41.0",
    "p_5000": "40.0",
    "year": ""
  },
  {
    "model": "G63-Remote",
    "category": "Car Charger",
    "type_cn": "车载FM发射器",
    "type_en": "Car FM Transmitter",
    "image": "images/G63-Standard.jpg",
    "bt": "BT 5.0",
    "ports": "PD",
    "signal": "10-15 m",
    "fm": "87.5-108.0 MHz",
    "selling": "🔌 Dual Cigarette Sockets​ - Power 2 devices simultaneously\n🎛 Wireless Steering Wheel Remote​ - Control music without touching device\n🔋 3A USB-C Fast Charging​ - Ultra-fast power delivery\nBonus: Bluetooth 5.3 + Battery voltage monitoring",
    "desc": "Bluetooth Version: V5.3\nWorking Voltage: 12V-24V\nVoltage Limit: 9-26V\nTransmission Distance: 10-15m\nOutput Ports: 2\nUSB Output: 5V/1A(Read USB Drive for Music Playback)\nType-C Output: PD 25W\n2-Port Power: 80W\nTF Card Slot: 1\nFM Frequency: 87.5-108.0MHz\nMicrophone Effective Distance: 0-1.0m\nBluetooth Effective Range: 10m\nFM Effective Range: 2-3m\n2Cigarette Lighter Sockets\nCertification: CE FCC RoHS Design Patent",
    "p_sample": "63.0",
    "p_500": "62.0",
    "p_2000": "61.0",
    "p_5000": "60.0",
    "dim": "85 x 75 x 60mm",
    "acc": "User Manual x1",
    "features": "Lossless Sound, Fast Charge, Voice Navigation, Hands-free Call, TF Card Slot, U Disk Play",
    "product_dim": "85 x 75 x 60mm",
    "box_dim": "108 x 165 x 85mm",
    "carton_dim": "44.5 x 34 x 56cm",
    "qty_carton": "50pcs/carton",
    "product_nw": "133.8g",
    "box_gw": "215.9g",
    "carton_gw": "",
    "year": ""
  },
  {
    "model": "GC06",
    "category": "Car Charger",
    "type_cn": "车载充电器",
    "type_en": "Car Charger",
    "image": "images/GC06-Standard.jpg",
    "power": "Total 120W",
    "ports": "3x USB-A, 2x USB-C",
    "cable": "1.0m",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "🔌 8-in-1 Power Hub​ - Combines 3 cigarette lighter sockets, 3 USB-A, and 2 USB-C ports in one device.\n⚡ 120W High Power​ - Supports high-power car appliances and fast charging for multiple devices simultaneously.\n🛡 Safe & Smart​ - Built-in car battery voltage display and comprehensive safety protections.",
    "desc": "1-to-3 Car Charger\nVoltage Range: 6-30V\nInput Voltage: 12V-24V\nOutput Ports: 5\nUSB 1 Output: 5V/3.1A\nUSB 2 Output: 5V/3.1A\nUSB 3 Output: QC3.0 Fast Charging\nType-C 1 Output: PD 35W\nType-C 2 Output: 5V/3.1A\nTotal Output Power: 120W\nProduct Material: Aluminum Alloy\n3Cigarette Lighter Sockets\nIndependent Switch Control\nPower Cable Length: 100cm\nCertification: CE FCC RoHS Design Patent",
    "p_sample": "43.0",
    "p_500": "42.0",
    "p_2000": "41.0",
    "p_5000": "40.0",
    "dim": "130 x 68 x 40mm\n46 x 20 x 65mm",
    "acc": "User Manual x1",
    "product_dim": "130 x 68 x 40mm\n46 x 20 x 65mm",
    "box_dim": "129 x 40 x 68mm",
    "product_nw": "193.0g",
    "box_gw": "250.0g",
    "carton_gw": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GC06-35W",
    "category": "Car Charger",
    "type_cn": "车载充电器",
    "type_en": "Car Charger",
    "image": "images/GC06-Standard.jpg",
    "power": "PD 35W | Total 120W",
    "ports": "3x USB-A | 2x USB-A | Type-C | PD | QC3.0",
    "cable": "1.0m",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "🔌 8-in-1 Power Hub​ - Combines 3 cigarette lighter sockets, 3 USB-A, and 2 USB-C ports in one device.\n⚡ 120W High Power​ - Supports high-power car appliances and fast charging for multiple devices simultaneously.\n🛡 Safe & Smart​ - Built-in car battery voltage display and comprehensive safety protections.",
    "desc": "1-to-3 Car Charger\nVoltage Range: 6-30V\nInput Voltage: 12V-24V\nOutput Ports: 5\nUSB 1 Output: 5V/3.1A\nUSB 2 Output: 5V/3.1A\nUSB 3 Output: QC3.0 Fast Charging\nType-C 1 Output: PD 35W\nType-C 2 Output: 5V/3.1A\nTotal Output Power: 120W\nProduct Material: Aluminum Alloy\n3Cigarette Lighter Sockets\nIndependent Switch Control\nPower Cable Length: 100cm\nCertification: CE FCC RoHS Design Patent",
    "p_sample": "43.0",
    "p_500": "42.0",
    "p_2000": "41.0",
    "p_5000": "40.0",
    "dim": "130 x 68 x 40mm\n46 x 20 x 65mm",
    "acc": "User Manual x1",
    "features": "LED Display, QC3.0, Smart Protection, Independent Switch, Universal for Cars",
    "proto": "QC3.0",
    "product_dim": "130 x 68 x 40mm\n46 x 20 x 65mm",
    "box_dim": "129 x 40 x 68mm",
    "product_nw": "193.0g",
    "box_gw": "250.0g",
    "carton_gw": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GC06-PD65W",
    "category": "Car Charger",
    "type_cn": "车载充电器",
    "type_en": "Car Charger",
    "image": "images/GC06-Standard.jpg",
    "power": "PD 65W | Total 120W",
    "ports": "3x USB-A | 2x USB-A | Type-C | PD | QC3.0",
    "cable": "1.0m",
    "input_v": "DC 12V",
    "material": "Fireproof PC + ABS",
    "cert": "CE, FCC, RoHS",
    "safety": "OCP, OVP, OTP, Short Circuit Protection",
    "selling": "🔌 8-in-1 Power Hub​ - Combines 3 cigarette lighter sockets, 3 USB-A, and 2 USB-C ports in one device.\n⚡ 120W High Power​ - Supports high-power car appliances and fast charging for multiple devices simultaneously.\n🛡 Safe & Smart​ - Built-in car battery voltage display and comprehensive safety protections.",
    "desc": "1-to-3 Car Charger\nVoltage Range: 6-30V\nInput Voltage: 12V-24V\nOutput Ports: 5\nUSB 1 Output: 5V/3.1A\nUSB 2 Output: 5V/3.1A\nUSB 3 Output: QC3.0 Fast Charging\nType-C 1 Output: PD 35W\nType-C 2 Output: 5V/3.1A\nTotal Output Power: 120W\nProduct Material: Aluminum Alloy\n3Cigarette Lighter Sockets\nIndependent Switch Control\nPower Cable Length: 100cm\nCertification: CE FCC RoHS Design Patent",
    "p_sample": "43.0",
    "p_500": "42.0",
    "p_2000": "41.0",
    "p_5000": "40.0",
    "dim": "130 x 68 x 40mm\n46 x 20 x 65mm",
    "acc": "User Manual x1",
    "features": "LED Display, QC3.0, Smart Protection, Independent Switch, Universal for Cars",
    "proto": "QC3.0",
    "product_dim": "130 x 68 x 40mm\n46 x 20 x 65mm",
    "box_dim": "129 x 40 x 68mm",
    "product_nw": "193.0g",
    "box_gw": "250.0g",
    "carton_gw": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "model": "GC11",
    "category": "Car Charger",
    "type_cn": "车载充电器",
    "type_en": "Car Charger",
    "image": "images/GC11.jpg",
    "desc": "Input Voltage: DC 12V-24V\nTotal Output Power: 120W (Max)\nUSB-C1\nPD Retractable Charging Cable Output: 5V 3.0A,9V 3.0A,12V 3.0A,15V 3.0A,20V 3.25A\n(24V vehicles support 15V/20V 65W Max, e.g. trucks, buses)\nUSB-C2+USB-A1+USB-A2 Output: 5V 3.6A (18W)\nTotal Output: Max 65W+18W\nPD Retractable Cable Total Length: 80cm (Effective Length 78cm±1cm)\nTotal Power Cable Length: 100cm",
    "dim": "130.6 x 91.2 x 38mm",
    "acc": "User Manual x1",
    "p_sample": "65.0",
    "p_500": "58.0",
    "p_2000": "57.0",
    "p_5000": "55.0",
    "product_dim": "130.6 x 91.2 x 38mm",
    "box_dim": "134 x 47 x 155mm",
    "carton_dim": "51.5 x 30.5 x 38cm",
    "qty_carton": "50pcs/carton",
    "product_nw": "216.2g",
    "box_gw": "257g",
    "carton_gw": "",
    "year": ""
  },
  {
    "model": "GC11S",
    "category": "Car Charger",
    "type_cn": "车载充电器",
    "type_en": "Car Charger",
    "image": "images/GC11S.jpg",
    "desc": "Input Voltage: DC 12V-24V\nTotal Output Power: 120W (Max)\nUSB-C1\nPD Retractable Charging Cable Output: 5V 3.0A,9V 3.0A,12V 3.0A,15V 3.0A,20V 3.25A\n(24V vehicles support 15V/20V 65W Max, e.g. trucks, buses)\nUSB-C2+USB-A1+USB-A2 Output: 5V 3.6A (18W)\nTotal Output: Max 65W+18W\nPD Retractable Cable Total Length: 80cm (Effective Length 78cm±1cm)\nTotal Power Cable Length: 100cm",
    "dim": "130.6 x 91.2 x 38mm",
    "acc": "User Manual x1",
    "power": "Total 120W",
    "ports": "3x USB-A, 3x USB-C",
    "features": "LED Display, Smart Protection, Independent Switch, Universal for Cars",
    "cable": "1.0m",
    "material": "Fireproof PC + ABS",
    "input_v": "DC 12V",
    "product_dim": "130.6 x 91.2 x 38mm",
    "box_dim": "134 x 47 x 155mm",
    "carton_dim": "51.5 x 30.5 x 38cm",
    "qty_carton": "50pcs/carton",
    "product_nw": "216.2g",
    "box_gw": "257g",
    "carton_gw": "",
    "p_sample": "70.0",
    "p_500": "70.0",
    "p_2000": "68.0",
    "p_5000": "65.0",
    "year": ""
  },
  {
    "model": "GC11-Pro",
    "category": "Car Charger",
    "type_cn": "车载充电器",
    "type_en": "Car Charger",
    "image": "images/GC11-Pro.jpg",
    "desc": "Input Voltage: DC 12V-24V\nTotal Output Power: 120W (Max)\nUSB-C1\nPD Retractable Charging Cable Output: 5V 3.0A,9V 3.0A,12V 3.0A,15V 3.0A,20V 3.25A\n(24V vehicles support 15V/20V 65W Max, e.g. trucks, buses)\nUSB-C2+USB-A1+USB-A2 Output: 5V 3.6A (18W)\nTotal Output: Max 65W+18W\nPD Retractable Cable Total Length: 80cm (Effective Length 78cm±1cm)\nTotal Power Cable Length: 100cm",
    "dim": "130.6 x 91.2 x 38mm",
    "acc": "User Manual x1",
    "p_sample": "65.0",
    "p_500": "58.0",
    "p_2000": "57.0",
    "p_5000": "55.0",
    "power": "Total 120W",
    "ports": "2x USB-A, 3x USB-C",
    "cable": "1.0m",
    "material": "Fireproof PC + ABS",
    "input_v": "DC 12V",
    "product_dim": "130.6 x 91.2 x 38mm",
    "box_dim": "134 x 47 x 155mm",
    "carton_dim": "51.5 x 30.5 x 38cm",
    "qty_carton": "50pcs/carton",
    "product_nw": "216.2g",
    "box_gw": "257g",
    "carton_gw": "",
    "year": ""
  },
  {
    "model": "ZNB01",
    "category": "Car Charger",
    "type_cn": "车载充电器",
    "type_en": "Car Charger",
    "image": "images/ZNB01.jpg",
    "desc": "Dual USB Multi-Function Car Charger\nVoltage Display Range: 6-30V\nInput Voltage: 12V-24V\nTotal Power: 80W\nOutput Ports:\nUSB 1 Output: 5V/1A\nUSB 2 Output: 5V/2.1A\nPower Cable Length: 50cm\n2Cigarette LighterInterface",
    "dim": "82 x 82 x 62mm",
    "acc": "1. User Manual x1\n2. Power Cable x1",
    "p_sample": "36.0",
    "p_500": "35.0",
    "p_2000": "34.0",
    "p_5000": "32.0",
    "product_dim": "82 x 82 x 62mm",
    "box_dim": "85 x 85 x 82mm",
    "carton_dim": "38 x 38 x 38cm",
    "qty_carton": "50pcs/carton",
    "product_nw": "155.0g",
    "box_gw": "190.0g",
    "carton_gw": "",
    "year": ""
  },
  {
    "category": "Car Charger",
    "type_cn": "伸缩线车充",
    "type_en": "Retractable Cable Car Charger",
    "dim": "61 x 33.5 x 153 mm",
    "weight": "143.8 g",
    "cable": "80CM",
    "p_sample": "50.0",
    "p_500": "45.0",
    "p_2000": "43.0",
    "p_5000": "42.0",
    "acc": "User Manual x1",
    "material": "Aluminum Alloy + PC + ABS",
    "input_v": "DC 12V-24V",
    "desc": "Output Ports: 4\nTotal Output: Max 90W\nInput: DC 12V-24V Max 5.0A\nPD Retractable Cable Output: 5V/3A,9V/3A,12V/3A,15V/3A,20V/3.25A(Max 65W)\niOS Retractable Charging Cable Output: 5V/2.4A\nUSB + Type-C Simultaneous Output: 5V/3.2A\nSolo Use Max Output: 5V/3A\nRetractable Cable Length: Total Length 80cm\n(Effective Length 78cm ± 1cm)\nCar Charger Material: Aluminum Alloy + PC + ABS\n7-Color LED Light: One-Touch Switch",
    "features": "Colorful Lights, Smart Protection, 360° Rotation, Universal for Cars",
    "image": "images/GC08-PD+L.jpg",
    "model": "GC08 PD+L",
    "power": "Total 65W+25W",
    "ports": "PD 65W + Lightning 12W | Retractable Cable",
    "product_nw": "143.8 g",
    "box_gw": "178 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "category": "Car Charger",
    "type_cn": "伸缩线车充",
    "type_en": "Retractable Cable Car Charger",
    "image": "images/GC08-PD+C.jpg",
    "dim": "61 x 33.5 x 153 mm",
    "weight": "143.8 g",
    "cable": "80CM",
    "p_sample": "50.0",
    "p_500": "45.0",
    "p_2000": "43.0",
    "p_5000": "42.0",
    "acc": "User Manual x1",
    "material": "Aluminum Alloy + PC + ABS",
    "input_v": "DC 12V-24V",
    "desc": "Output Ports: 4\nTotal Output: Max 90W\nInput: DC 12V-24V Max 5.0A\nPD Retractable Cable Output: 5V/3A,9V/3A,12V/3A,15V/3A,20V/3.25A(Max 65W)\nUSB-C Retractable Cable Output: 5V/3A,9V/2A,12V/1.5A (18W)\nUSB + Type-C Simultaneous Output: 5V/3.2A\nSolo Use Max Output: 5V/3A\nRetractable Cable Length: Total Length 80cm\n(Effective Length 78cm ± 1cm)\nCar Charger Material: Aluminum Alloy + PC + ABS\n7-Color LED Light: One-Touch Switch",
    "features": "Colorful Lights, Smart Protection, 360° Rotation, Universal for Cars",
    "model": "GC08 PD+C",
    "power": "Total 65W+25W",
    "ports": "PD 65W + USB-C 18W | Retractable Cable",
    "product_nw": "143.8 g",
    "box_gw": "178 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "category": "Car Charger",
    "type_cn": "伸缩线车充",
    "type_en": "Retractable Cable Car Charger",
    "image": "images/GC08-2PD.jpg",
    "dim": "61 x 33.5 x 153 mm",
    "weight": "143.8 g",
    "cable": "80CM",
    "p_sample": "50.0",
    "p_500": "45.0",
    "p_2000": "43.0",
    "p_5000": "42.0",
    "acc": "User Manual x1",
    "material": "Aluminum Alloy + PC + ABS",
    "input_v": "DC 12V-24V",
    "desc": "Output Ports: 4\nTotal Output: Max 90W\nInput: DC 12V-24V Max 5.0A\nPD Retractable Cable Output: 5V/3A,9V/3A,12V/3A,15V/3A,20V/3.25A(Max 65W)\nPD Retractable Cable 2 Output: 5V/3A,9V/3A,12V/3A,15V/3A,20V/3.25A (Max 65W)\nUSB + Type-C Simultaneous Output: 5V/3.2A\nSolo Use Max Output: 5V/3A\nRetractable Cable Length: Total Length 80cm\n(Effective Length 78cm ± 1cm)\nCar Charger Material: Aluminum Alloy + PC + ABS\n7-Color LED Light: One-Touch Switch",
    "features": "Colorful Lights, Smart Protection, 360° Rotation, Universal for Cars",
    "model": "GC08 2PD",
    "power": "Total 65W+65W",
    "ports": "Dual PD 65W | Retractable Cable",
    "product_nw": "143.8 g",
    "box_gw": "178 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "year": ""
  },
  {
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/GC08.jpg",
    "dim": "61 x 33.5 x 153 mm",
    "weight": "143.8 g",
    "cable": "80CM",
    "acc": "User Manual x1",
    "material": "Aluminum Alloy + PC + ABS",
    "input_v": "DC 12V-24V",
    "desc": "Output Ports: 4\nTotal Output: Max 90W\nInput: DC 12V-24V Max 5.0A\nPD Retractable Cable Output: 5V/3A,9V/3A,12V/3A,15V/3A,20V/3.25A(Max 65W)\niOS Retractable Charging Cable Output: 5V/2.4A\nUSB + Type-C Simultaneous Output: 5V/3.2A\nSolo Use Max Output: 5V/3A\nRetractable Cable Length: Total Length 80cm\n(Effective Length 78cm ± 1cm)\nCar Charger Material: Aluminum Alloy + PC + ABS\n7-Color LED Light: One-Touch Switch",
    "features": "Colorful Lights, Smart Protection, 360° Rotation, Universal for Cars",
    "model": "GC08-FM(PD+L)",
    "power": "Total 65W+25W",
    "ports": "PD 65W + Lightning 12W | Retractable Cable",
    "bt": "BT 5.4",
    "fm": "87.5-108MHz",
    "selling": "⚡ PD 65W Fast Charge + Lightning Cable\n🎵 Bluetooth 5.4 FM Transmitter\n🌈 7-Color LED Light with One-Touch Switch",
    "product_nw": "143.8 g",
    "box_gw": "178 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "p_sample": "55.0",
    "p_500": "54.0",
    "p_2000": "53.0",
    "p_5000": "52.0",
    "year": ""
  },
  {
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/GC08.jpg",
    "dim": "61 x 33.5 x 153 mm",
    "weight": "143.8 g",
    "cable": "80CM",
    "acc": "User Manual x1",
    "material": "Aluminum Alloy + PC + ABS",
    "input_v": "DC 12V-24V",
    "desc": "Output Ports: 4\nTotal Output: Max 90W\nInput: DC 12V-24V Max 5.0A\nPD Retractable Cable Output: 5V/3A,9V/3A,12V/3A,15V/3A,20V/3.25A(Max 65W)\nUSB-C Retractable Cable Output: 5V/3A,9V/2A,12V/1.5A (18W)\nUSB + Type-C Simultaneous Output: 5V/3.2A\nSolo Use Max Output: 5V/3A\nRetractable Cable Length: Total Length 80cm\n(Effective Length 78cm ± 1cm)\nCar Charger Material: Aluminum Alloy + PC + ABS\n7-Color LED Light: One-Touch Switch",
    "features": "Colorful Lights, Smart Protection, 360° Rotation, Universal for Cars",
    "model": "GC08-FM(PD+C)",
    "power": "Total 65W+25W",
    "ports": "PD 65W + USB-C 18W | Retractable Cable",
    "bt": "BT 5.4",
    "fm": "87.5-108MHz",
    "selling": "⚡ PD 65W Fast Charge + USB-C Cable\n🎵 Bluetooth 5.4 FM Transmitter\n🌈 7-Color LED Light with One-Touch Switch",
    "product_nw": "143.8 g",
    "box_gw": "178 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "p_sample": "55.0",
    "p_500": "54.0",
    "p_2000": "53.0",
    "p_5000": "52.0",
    "year": ""
  },
  {
    "category": "Car Bluetooth MP3",
    "type_cn": "车载蓝牙MP3",
    "type_en": "Car MP3 Player",
    "image": "images/GC08.jpg",
    "dim": "61 x 33.5 x 153 mm",
    "weight": "143.8 g",
    "cable": "80CM",
    "acc": "User Manual x1",
    "material": "Aluminum Alloy + PC + ABS",
    "input_v": "DC 12V-24V",
    "desc": "Output Ports: 4\nTotal Output: Max 90W\nInput: DC 12V-24V Max 5.0A\nPD Retractable Cable Output: 5V/3A,9V/3A,12V/3A,15V/3A,20V/3.25A(Max 65W)\nPD Retractable Cable 2 Output: 5V/3A,9V/3A,12V/3A,15V/3A,20V/3.25A (Max 65W)\nUSB + Type-C Simultaneous Output: 5V/3.2A\nSolo Use Max Output: 5V/3A\nRetractable Cable Length: Total Length 80cm\n(Effective Length 78cm ± 1cm)\nCar Charger Material: Aluminum Alloy + PC + ABS\n7-Color LED Light: One-Touch Switch",
    "features": "Colorful Lights, Smart Protection, 360° Rotation, Universal for Cars",
    "model": "GC08-FM(2PD)",
    "power": "Total 65W+65W",
    "ports": "Dual PD 65W | Retractable Cable",
    "bt": "BT 5.4",
    "fm": "87.5-108MHz",
    "selling": "⚡ Dual PD 65W Fast Charge\n🎵 Bluetooth 5.4 FM Transmitter\n🌈 7-Color LED Light with One-Touch Switch",
    "product_nw": "143.8 g",
    "box_gw": "178 g",
    "carton_gw": "",
    "product_dim": "",
    "box_dim": "",
    "carton_dim": "",
    "qty_carton": "",
    "p_sample": "55.0",
    "p_500": "54.0",
    "p_2000": "53.0",
    "p_5000": "52.0",
    "year": ""
  }
  ];
